module.exports = [
  {
    id: "attack-on-titan",
    title: "Attack on Titan",
    originalTitle: "進撃の巨人 (Shingeki no Kyojin)",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/yQxGv61nFqZ0nL0uF306b9qC0oT.jpg",
    rating: 9.1,
    ratingCount: "3.8M",
    year: 2013,
    ongoing: false,
    runtimeOrChapters: "89 Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Dark Fantasy", "Post-Apocalyptic", "Mystery"],
    platformOrStudio: "WIT Studio / MAPPA",
    synopsis: "After his hometown is destroyed and his mother is killed, Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
    quote: "IF YOU WIN, YOU LIVE. IF YOU LOSE, YOU DIE. IF YOU DON'T FIGHT, YOU CANNOT WIN!",
    rank: "Rank #1 Dark Fantasy Anime",
    membersCount: "3.8M Members",
    trailerUrl: "https://www.youtube.com/embed/MGRm4IzK1SQ",
    featured: true,
    trending: true,
    tags: ["Titans", "Scout Regiment", "Eren Jaeger", "Rumbling", "MAPPA"],
    totalUnits: 89,
    unitType: "episodes",
    topArcs: [
      { title: "Fall of Shiganshina", range: "Ep. 1 - 2", description: "The Colossal Titan breaches Wall Maria.", status: "Tragic" },
      { title: "Return to Shiganshina", range: "Ep. 49 - 59", description: "The battle for the basement secrets and Erwin's charge.", status: "Masterpiece" },
      { title: "The Rumbling", range: "Final Chapters", description: "Eren activates the Wall Titans to flatten the world.", status: "Climax" }
    ]
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    originalTitle: "呪術廻戦",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/gmECX1DvE9RiTeiKVPV7ndJTX8o.jpg",
    rating: 8.8,
    ratingCount: "2.4M",
    year: 2020,
    ongoing: true,
    runtimeOrChapters: "47 Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Supernatural", "Dark Fantasy", "Shonen"],
    platformOrStudio: "MAPPA",
    synopsis: "High schooler Yuji Itadori swallows a cursed finger of the King of Curses Ryomen Sukuna and is thrust into the deadly secret war of Jujutsu Sorcerers.",
    quote: "THROUGHOUT HEAVEN AND EARTH, I ALONE AM THE HONORED ONE.",
    rank: "Rank #2 Modern Shonen",
    membersCount: "2.4M Members",
    trailerUrl: "https://www.youtube.com/embed/f7kWURvUpnE",
    featured: true,
    trending: true,
    tags: ["Cursed Energy", "Domain Expansion", "Gojo", "Sukuna", "MAPPA"],
    totalUnits: 47,
    unitType: "episodes",
    topArcs: [
      { title: "Kyoto Goodwill Event", range: "Ep. 14 - 21", description: "Inter-school battle showcasing Black Flash.", status: "Action" },
      { title: "Shibuya Incident", range: "S2 Ep. 6 - 23", description: "The catastrophe that seals Gojo and destroys Shibuya.", status: "Masterpiece" }
    ]
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer: Kimetsu no Yaiba",
    originalTitle: "鬼滅の刃",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/nTvM4mhqZlHIvUkI1gVnW6XP7GG.jpg",
    rating: 8.7,
    ratingCount: "2.9M",
    year: 2019,
    ongoing: true,
    runtimeOrChapters: "55 Episodes + Movies",
    ageRating: "TV-14",
    genres: ["Action", "Supernatural", "Historical", "Fantasy"],
    platformOrStudio: "ufotable",
    synopsis: "Tanjiro Kamado sets out on a perilous path to become a Demon Slayer to avenge his slaughtered family and find a cure to turn his demonized sister Nezuko back into a human.",
    quote: "SET YOUR HEART ABLAZE!",
    rank: "Rank #1 Box Office Phenomenon",
    membersCount: "2.9M Members",
    trailerUrl: "https://www.youtube.com/embed/6vMuWuWlW4I",
    featured: true,
    trending: true,
    tags: ["Breathing Styles", "ufotable", "Hashira", "Mugen Train", "Nezuko"],
    totalUnits: 55,
    unitType: "episodes"
  },
  {
    id: "fullmetal-alchemist-brotherhood",
    title: "Fullmetal Alchemist: Brotherhood",
    originalTitle: "鋼の錬金術師 FULLMETAL ALCHEMIST",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1223/96541.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/2rmK7mnchq9fd8dnfZ52cqQx7MN.jpg",
    rating: 9.3,
    ratingCount: "3.2M",
    year: 2009,
    ongoing: false,
    runtimeOrChapters: "64 Episodes",
    ageRating: "TV-14",
    genres: ["Action", "Adventure", "Fantasy", "Drama"],
    platformOrStudio: "Bones",
    synopsis: "Two brothers search for a Philosopher's Stone after an attempt to revive their deceased mother goes awry and leaves them in damaged physical forms.",
    quote: "A LESSON WITHOUT PAIN IS MEANINGLESS.",
    rank: "Rank #1 Highest Rated Anime of All Time",
    membersCount: "3.2M Members",
    trailerUrl: "https://www.youtube.com/embed/d3q4dI3aX0Q",
    featured: true,
    tags: ["Alchemy", "Elric Brothers", "Philosophers Stone", "Father", "Bones"],
    totalUnits: 64,
    unitType: "episodes"
  },
  {
    id: "death-note",
    title: "Death Note",
    originalTitle: "デスノート",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/9/9453.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/iA5L1P0gG6m35eF1VqBqO01Z1z0.jpg",
    rating: 9.0,
    ratingCount: "3.7M",
    year: 2006,
    ongoing: false,
    runtimeOrChapters: "37 Episodes",
    ageRating: "TV-14",
    genres: ["Psychological", "Supernatural", "Thriller", "Mystery"],
    platformOrStudio: "Madhouse",
    synopsis: "A high school prodigy discovers a supernatural notebook that grants him the power to kill anyone whose name he writes in it, igniting a global cat-and-mouse chase with a mysterious genius detective.",
    quote: "I'LL TAKE A POTATO CHIP... AND EAT IT!",
    rank: "Rank #1 Psychological Thriller",
    membersCount: "3.7M Members",
    trailerUrl: "https://www.youtube.com/embed/tPEE9ZWXXW0",
    tags: ["Light Yagami", "L", "Shinigami", "Ryuk", "Madhouse"],
    totalUnits: 37,
    unitType: "episodes"
  },
  {
    id: "steins-gate",
    title: "Steins;Gate",
    originalTitle: "シュタインズ・ゲート",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1935/127974.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/5n2P0F537K8Nl559Z9W3UvE3k2N.jpg",
    rating: 9.1,
    ratingCount: "2.4M",
    year: 2011,
    ongoing: false,
    runtimeOrChapters: "24 Episodes",
    ageRating: "TV-14",
    genres: ["Sci-Fi", "Psychological", "Thriller", "Drama"],
    platformOrStudio: "White Fox",
    synopsis: "Self-proclaimed mad scientist Rintaro Okabe accidentally invents a microwave that sends text messages into the past, unraveling a deadly timeline conflict against a shadowy global conspiracy.",
    quote: "EL PSY KONGROO.",
    rank: "Rank #2 Sci-Fi Anime",
    membersCount: "2.4M Members",
    trailerUrl: "https://www.youtube.com/embed/uMYhjVwp0Fk",
    tags: ["Time Travel", "Mad Scientist", "Kurisu", "Okabe", "World Line"],
    totalUnits: 24,
    unitType: "episodes"
  },
  {
    id: "hunter-x-hunter-2011",
    title: "Hunter x Hunter (2011)",
    originalTitle: "HUNTER×HUNTER",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1337/99013.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/q6i04M5K65C17b5B2A9pA1jF4g0.jpg",
    rating: 9.0,
    ratingCount: "2.6M",
    year: 2011,
    ongoing: false,
    runtimeOrChapters: "148 Episodes",
    ageRating: "TV-14",
    genres: ["Action", "Adventure", "Fantasy", "Shonen"],
    platformOrStudio: "Madhouse",
    synopsis: "Gon Freecss discovers that his father is a world-renowned licensed Hunter. Setting out on the grueling Hunter Exam, he makes lifelong comrades and confronts the darkness of humanity.",
    quote: "YOU SHOULD ENJOY THE LITTLE DETOURS TO THE FULLEST.",
    rank: "Rank #3 All-Time Anime",
    membersCount: "2.6M Members",
    trailerUrl: "https://www.youtube.com/embed/d6kBeJjTGnY",
    tags: ["Nen", "Chimera Ant", "Killua", "Gon", "Hisoka"],
    totalUnits: 148,
    unitType: "episodes"
  },
  {
    id: "bleach-tybw",
    title: "Bleach: Thousand-Year Blood War",
    originalTitle: "BLEACH 千年血戦篇",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1764/126627.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/2wWh7028h7nFwS60N8qF38B8A0E.jpg",
    rating: 8.9,
    ratingCount: "680K",
    year: 2022,
    ongoing: true,
    runtimeOrChapters: "26+ Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Supernatural", "Fantasy", "Shonen"],
    platformOrStudio: "Studio Pierrot",
    synopsis: "The peace of Soul Society is shattered when the Quincy army under Emperor Yhwach invades, declaring an extinction war against the Shinigami.",
    quote: "BANKAI.",
    rank: "Rank #1 Comeback Anime",
    membersCount: "680K Members",
    trailerUrl: "https://www.youtube.com/embed/78WIYzX_B68",
    tags: ["Ichigo", "Soul Reaper", "Quincy", "Bankai", "Pierrot"],
    totalUnits: 52,
    unitType: "episodes"
  },
  {
    id: "chainsaw-man",
    title: "Chainsaw Man",
    originalTitle: "チェンソーマン",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/eU0Tg9n7pD3F5qFzZ3jU7a2V7uT.jpg",
    rating: 8.5,
    ratingCount: "1.4M",
    year: 2022,
    ongoing: true,
    runtimeOrChapters: "12 Episodes + Film",
    ageRating: "TV-MA",
    genres: ["Action", "Dark Fantasy", "Supernatural", "Gore"],
    platformOrStudio: "MAPPA",
    synopsis: "Denji, a teenage boy living in extreme poverty with a chainsaw devil named Pochita, is resurrected as a Devil-Human hybrid and recruited into the Public Safety Devil Hunters.",
    quote: "ALL DEVILS ARE BORN WITH A NAME.",
    rank: "Rank #1 Viral Shonen",
    membersCount: "1.4M Members",
    trailerUrl: "https://www.youtube.com/embed/q15CRdE5Bv0",
    tags: ["Denji", "Makima", "Power", "Devils", "MAPPA"],
    totalUnits: 12,
    unitType: "episodes"
  },
  {
    id: "neon-genesis-evangelion",
    title: "Neon Genesis Evangelion",
    originalTitle: "新世紀エヴァンゲリオン",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1314/108941.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/nQ4iV63Kq2GqZ3kM8p0V2uF6m1N.jpg",
    rating: 8.4,
    ratingCount: "1.8M",
    year: 1995,
    ongoing: false,
    runtimeOrChapters: "26 Episodes + End of Evangelion",
    ageRating: "TV-14",
    genres: ["Mecha", "Psychological", "Sci-Fi", "Drama"],
    platformOrStudio: "Gainax / Tatsunoko",
    synopsis: "In 2015, fourteen-year-old Shinji Ikari is summoned by his estranged father to pilot a giant biological mecha called EVA-01 against cataclysmic alien invaders named Angels.",
    quote: "GET IN THE ROBOT, SHINJI.",
    rank: "Rank #1 Masterpiece Mecha",
    membersCount: "1.8M Members",
    trailerUrl: "https://www.youtube.com/embed/13nSISwxrY4",
    tags: ["Shinji", "Asuka", "Rei", "Angels", "Psychological"],
    totalUnits: 26,
    unitType: "episodes"
  },
  {
    id: "cowboy-bebop",
    title: "Cowboy Bebop",
    originalTitle: "カウボーイビバップ",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/4/19644.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/uCu4jN6r2F5pT5L7cQ7z0m0z0bE.jpg",
    rating: 8.8,
    ratingCount: "1.7M",
    year: 1998,
    ongoing: false,
    runtimeOrChapters: "26 Episodes",
    ageRating: "TV-14",
    genres: ["Sci-Fi", "Action", "Space Western", "Noir"],
    platformOrStudio: "Sunrise",
    synopsis: "In the year 2071, an eccentric crew of bounty hunters travel across the solar system aboard the Bebop, haunted by their pasts while chasing criminal bounties.",
    quote: "SEE YOU SPACE COWBOY...",
    rank: "Rank #1 Space Noir",
    membersCount: "1.7M Members",
    trailerUrl: "https://www.youtube.com/embed/L-tw_3lR3kQ",
    tags: ["Spike Spiegel", "Jazz", "Yoko Kanno", "Bebop", "Noir"],
    totalUnits: 26,
    unitType: "episodes"
  },
  {
    id: "naruto-shippuden",
    title: "Naruto: Shippuden",
    originalTitle: "NARUTO -ナルト- 疾風伝",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1565/111305.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/vFlq03Xl3gJ5vB8k9M1P4E2m3X8.jpg",
    rating: 8.3,
    ratingCount: "2.8M",
    year: 2007,
    ongoing: false,
    runtimeOrChapters: "500 Episodes",
    ageRating: "TV-14",
    genres: ["Action", "Adventure", "Fantasy", "Shonen"],
    platformOrStudio: "Studio Pierrot",
    synopsis: "Naruto Uzumaki returns to the Hidden Leaf Village after years of intense training, determined to save his rogue friend Sasuke and defeat the Akatsuki organization.",
    quote: "I NEVER GO BACK ON MY WORD. THAT'S MY NINJA WAY!",
    rank: "Rank #1 Ninja Epic",
    membersCount: "2.8M Members",
    trailerUrl: "https://www.youtube.com/embed/1W1sZ2nQYtM",
    tags: ["Shinobi", "Rasengan", "Akatsuki", "Sasuke", "Hokage"],
    totalUnits: 500,
    unitType: "episodes"
  },
  {
    id: "code-geass",
    title: "Code Geass: Lelouch of the Rebellion",
    originalTitle: "コードギアス 反逆のルルーシュ",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1032/135088.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/7eHn2P5Z0m2P1V6E4L2U9m8N7x1.jpg",
    rating: 8.7,
    ratingCount: "2.2M",
    year: 2006,
    ongoing: false,
    runtimeOrChapters: "50 Episodes",
    ageRating: "TV-14",
    genres: ["Mecha", "Military", "Sci-Fi", "Suspense"],
    platformOrStudio: "Sunrise",
    synopsis: "An exiled Britannian prince acquires the supernatural power of absolute command known as Geass and dons a mask as Zero to dismantle the tyrannical empire.",
    quote: "THE ONLY ONES WHO SHOULD KILL ARE THOSE PREPARED TO BE KILLED.",
    rank: "Rank #1 Tactical Mastermind",
    membersCount: "2.2M Members",
    trailerUrl: "https://www.youtube.com/embed/O9aU68j3nN4",
    tags: ["Lelouch", "Zero", "Geass", "Britannia", "Mecha"],
    totalUnits: 50,
    unitType: "episodes"
  },
  {
    id: "haikyuu",
    title: "Haikyuu!!",
    originalTitle: "ハイキュー!!",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/7/76014.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/m9kP4V1k3N0Q9p4m7U8E2v1x9yP.jpg",
    rating: 8.5,
    ratingCount: "1.9M",
    year: 2014,
    ongoing: false,
    runtimeOrChapters: "85 Episodes + Movies",
    ageRating: "TV-14",
    genres: ["Sports", "Comedy", "Drama", "Shonen"],
    platformOrStudio: "Production I.G",
    synopsis: "Determined to be like the legendary 'Little Giant', the diminutive Shoyo Hinata joins Karasuno High's volleyball club, teaming up with his former rival Tobio Kageyama.",
    quote: "DOES SOMEONE NEED A REASON NOT TO LOSE?",
    rank: "Rank #1 Sports Anime",
    membersCount: "1.9M Members",
    trailerUrl: "https://www.youtube.com/embed/JOGp287-kGo",
    tags: ["Volleyball", "Karasuno", "Hinata", "Kageyama", "Spike"],
    totalUnits: 85,
    unitType: "episodes"
  },
  {
    id: "mob-psycho-100",
    title: "Mob Psycho 100",
    originalTitle: "モブサイコ100",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/8/80356.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/r2Vq7M6Q9Y2K6N8V1X9Z3p4b8U5.jpg",
    rating: 8.5,
    ratingCount: "1.9M",
    year: 2016,
    ongoing: false,
    runtimeOrChapters: "37 Episodes",
    ageRating: "TV-14",
    genres: ["Action", "Comedy", "Supernatural"],
    platformOrStudio: "Bones",
    synopsis: "Shigeo 'Mob' Kageyama is an eighth-grader with formidable psychic powers who wants nothing more than to live a normal life while keeping his emotional counter under 100%.",
    quote: "IF EVERYONE IS NOT SPECIAL, MAYBE YOU CAN BE WHAT YOU WANT TO BE.",
    rank: "Rank #1 Sakuga Animation",
    membersCount: "1.9M Members",
    trailerUrl: "https://www.youtube.com/embed/notKMY2Fv84",
    tags: ["Esper", "Reigen", "Bones", "Psychic", "Growth"],
    totalUnits: 37,
    unitType: "episodes"
  },
  {
    id: "spy-x-family",
    title: "Spy x Family",
    originalTitle: "SPY×FAMILY",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1441/122795.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/tC3P1K9n7q8E2m5N4X6p8V1x9yP.jpg",
    rating: 8.5,
    ratingCount: "1.6M",
    year: 2022,
    ongoing: true,
    runtimeOrChapters: "37 Episodes + Movie",
    ageRating: "TV-14",
    genres: ["Action", "Comedy", "Slice of Life"],
    platformOrStudio: "Wit Studio / CloverWorks",
    synopsis: "Master spy Twilight creates a fabricated family to infiltrate an elite school, unaware his adopted daughter is a telepath and his fake wife is a lethal assassin.",
    quote: "WAKU WAKU!",
    rank: "Rank #1 Family Action Comedy",
    membersCount: "1.6M Members",
    trailerUrl: "https://www.youtube.com/embed/ofXigq9aIpo",
    tags: ["Anya", "Loid Forger", "Yor", "Espionage", "Wholesome"],
    totalUnits: 37,
    unitType: "episodes"
  },
  {
    id: "one-punch-man",
    title: "One Punch Man",
    originalTitle: "ワンパンマン",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/12/76049.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/gL0bU9a0Z1N6X8k3P2q8V1x9yP.jpg",
    rating: 8.5,
    ratingCount: "3.1M",
    year: 2015,
    ongoing: true,
    runtimeOrChapters: "24 Episodes",
    ageRating: "TV-14",
    genres: ["Action", "Comedy", "Superhero", "Parody"],
    platformOrStudio: "Madhouse / J.C.Staff",
    synopsis: "Saitama has trained so hard he can defeat any adversary with a single punch, leading him into an existential crisis of sheer boredom.",
    quote: "I'M JUST A GUY WHO'S A HERO FOR FUN.",
    rank: "Rank #1 Superhero Parody",
    membersCount: "3.1M Members",
    trailerUrl: "https://www.youtube.com/embed/2JAElThbKrI",
    tags: ["Saitama", "Genos", "Hero Association", "Madhouse", "Overpowered"],
    totalUnits: 24,
    unitType: "episodes"
  },
  {
    id: "my-hero-academia",
    title: "My Hero Academia",
    originalTitle: "僕のヒーローアカデミア",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/10/78745.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/eZg3Z2v5X9p7Q8M6N4X6p8V1x9yP.jpg",
    rating: 7.9,
    ratingCount: "2.9M",
    year: 2016,
    ongoing: true,
    runtimeOrChapters: "159 Episodes",
    ageRating: "TV-14",
    genres: ["Action", "Superhero", "School", "Shonen"],
    platformOrStudio: "Bones",
    synopsis: "In a world where 80% of humanity possesses superpowers called Quirks, the powerless Izuku Midoriya catches the eye of All Might, the greatest hero of all.",
    quote: "PLUS ULTRA!",
    rank: "Rank #2 Modern Superhero",
    membersCount: "2.9M Members",
    trailerUrl: "https://www.youtube.com/embed/D5fy4e4A8Wk",
    tags: ["Deku", "All Might", "Quirks", "Bones", "Shonen"],
    totalUnits: 159,
    unitType: "episodes"
  },
  {
    id: "oshi-no-ko",
    title: "Oshi no Ko",
    originalTitle: "【推しの子】",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1812/134736.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/c8Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.7,
    ratingCount: "820K",
    year: 2023,
    ongoing: true,
    runtimeOrChapters: "24 Episodes",
    ageRating: "TV-14",
    genres: ["Drama", "Mystery", "Supernatural"],
    platformOrStudio: "Doga Kobo",
    synopsis: "A gynecologist and his deceased patient are reborn as the twin children of their favorite pop idol Ai Hoshino, plunging into the cutthroat realities of the entertainment industry.",
    quote: "LIES ARE AN IDOL'S GREATEST LOVE.",
    rank: "Rank #1 Industry Thriller",
    membersCount: "820K Members",
    trailerUrl: "https://www.youtube.com/embed/g3b7tXq4d2M",
    tags: ["Ai Hoshino", "Idol", "Aqua", "Mystery", "Showbiz"],
    totalUnits: 24,
    unitType: "episodes"
  },
  {
    id: "bocchi-the-rock",
    title: "Bocchi the Rock!",
    originalTitle: "ぼっち・ざ・ろっく！",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1448/127956.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/d9Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.8,
    ratingCount: "650K",
    year: 2022,
    ongoing: false,
    runtimeOrChapters: "12 Episodes",
    ageRating: "PG-13",
    genres: ["Comedy", "Music", "Slice of Life"],
    platformOrStudio: "CloverWorks",
    synopsis: "Hitori Gotoh is an extremely socially anxious guitarist who spends all her time practicing in her closet until she is suddenly drafted into a four-piece indie rock band.",
    quote: "ROCK WILL SAVE THE INTROVERTS.",
    rank: "Rank #1 Indie Music Anime",
    membersCount: "650K Members",
    trailerUrl: "https://www.youtube.com/embed/a7g0A_g6f8Q",
    tags: ["Kessoku Band", "Guitar", "Introvert", "CloverWorks", "Sakuga"],
    totalUnits: 12,
    unitType: "episodes"
  },
  {
    id: "violet-evergarden",
    title: "Violet Evergarden",
    originalTitle: "ヴァイオレット・エヴァーガーデン",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1795/95088.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/p2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.7,
    ratingCount: "1.7M",
    year: 2018,
    ongoing: false,
    runtimeOrChapters: "13 Episodes + Movie",
    ageRating: "TV-14",
    genres: ["Drama", "Fantasy", "Slice of Life"],
    platformOrStudio: "Kyoto Animation",
    synopsis: "A former child soldier prosthetic arm typist works as an Auto Memory Doll, transcribing the heartfelt emotions of others while searching for the meaning of 'I love you'.",
    quote: "I WANT TO KNOW WHAT 'I LOVE YOU' MEANS.",
    rank: "Rank #1 Kyoto Animation Visuals",
    membersCount: "1.7M Members",
    trailerUrl: "https://www.youtube.com/embed/g5xWqjF9MZU",
    tags: ["Kyoto Animation", "Letters", "Tears", "War", "Masterpiece"],
    totalUnits: 13,
    unitType: "episodes"
  },
  {
    id: "gurren-lagann",
    title: "Tengen Toppa Gurren Lagann",
    originalTitle: "天元突破グレンラガン",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/4/5123.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/x2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.6,
    ratingCount: "1.5M",
    year: 2007,
    ongoing: false,
    runtimeOrChapters: "27 Episodes",
    ageRating: "TV-14",
    genres: ["Action", "Adventure", "Mecha", "Sci-Fi"],
    platformOrStudio: "Gainax",
    synopsis: "In a subterranean world, digger boy Simon and hot-headed Kamina break through the ceiling of Earth to fight tyrannical Beastmen with a drill that will pierce the heavens.",
    quote: "BELIEVE IN THE ME THAT BELIEVES IN YOU!",
    rank: "Rank #1 Hype Mecha",
    membersCount: "1.5M Members",
    trailerUrl: "https://www.youtube.com/embed/k5kPfZkL6Hw",
    tags: ["Spiral Power", "Kamina", "Simon", "Drill", "Gainax"],
    totalUnits: 27,
    unitType: "episodes"
  },
  {
    id: "rezero",
    title: "Re:Zero - Starting Life in Another World",
    originalTitle: "Re:ゼロから始める異世界生活",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1522/128039.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/y2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.3,
    ratingCount: "2.1M",
    year: 2016,
    ongoing: true,
    runtimeOrChapters: "50+ Episodes",
    ageRating: "TV-MA",
    genres: ["Psychological", "Dark Fantasy", "Isekai", "Suspense"],
    platformOrStudio: "White Fox",
    synopsis: "Subaru Natsuki is summoned to a fantasy world where he discovers he cannot die permanently; instead, death rewinds time, forcing him to suffer trauma repeatedly to save those he loves.",
    quote: "RETURN BY DEATH.",
    rank: "Rank #1 Dark Isekai",
    membersCount: "2.1M Members",
    trailerUrl: "https://www.youtube.com/embed/vFbg3Zp8h4M",
    tags: ["Subaru", "Rem", "Emilia", "White Fox", "Time Loop"],
    totalUnits: 50,
    unitType: "episodes"
  },
  {
    id: "mushoku-tensei",
    title: "Mushoku Tensei: Jobless Reincarnation",
    originalTitle: "無職転生 ～異世界行ったら本気だす～",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1530/117776.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/z2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.7,
    ratingCount: "1.2M",
    year: 2021,
    ongoing: true,
    runtimeOrChapters: "48 Episodes",
    ageRating: "TV-MA",
    genres: ["Fantasy", "Adventure", "Drama", "Isekai"],
    platformOrStudio: "Studio Bind",
    synopsis: "A 34-year-old shut-in dies saving strangers and reincarnates into a world of swords and sorcery as Rudeus Greyrat, determined to live his second life to the absolute fullest.",
    quote: "I WILL LIVE THIS LIFE WITHOUT REGRETS.",
    rank: "Rank #1 High Fantasy Isekai",
    membersCount: "1.2M Members",
    trailerUrl: "https://www.youtube.com/embed/Qx4j4S1i0kY",
    tags: ["Rudeus", "Studio Bind", "Worldbuilding", "Magic", "Eris"],
    totalUnits: 48,
    unitType: "episodes"
  },
  {
    id: "made-in-abyss",
    title: "Made in Abyss",
    originalTitle: "メイドインアビス",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/6/86733.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/w2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.7,
    ratingCount: "1.3M",
    year: 2017,
    ongoing: true,
    runtimeOrChapters: "25 Episodes + Movies",
    ageRating: "TV-MA",
    genres: ["Adventure", "Dark Fantasy", "Sci-Fi", "Mystery"],
    platformOrStudio: "Kinema Citrus",
    synopsis: "An orphaned girl named Riko and a robotic boy named Reg descend into the colossal, unexplored chasm known as the Abyss in search of Riko's legendary mother.",
    quote: "THE ABYSS REWARDS THE CURIOUS WITH CATASTROPHE.",
    rank: "Rank #1 World Exploration",
    membersCount: "1.3M Members",
    trailerUrl: "https://www.youtube.com/embed/AQx_KKY1sDU",
    tags: ["Abyss", "Kinema Citrus", "Kevin Penkin", "Dark Fantasy", "Reg"],
    totalUnits: 25,
    unitType: "episodes"
  },
  {
    id: "hells-paradise",
    title: "Hell's Paradise",
    originalTitle: "地獄楽 (Jigokuraku)",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1826/133604.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/v2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.2,
    ratingCount: "680K",
    year: 2023,
    ongoing: true,
    runtimeOrChapters: "13 Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Dark Fantasy", "Historical", "Supernatural"],
    platformOrStudio: "MAPPA",
    synopsis: "Sentenced to death, the hollow ninja Gabimaru is given a chance at a royal pardon if he retrieves the Elixir of Immortality from a sinister island inhabited by abominable deities.",
    quote: "A HOLLOW MAN FEELS NO PAIN.",
    rank: "Rank #3 Dark Trio Shonen",
    membersCount: "680K Members",
    trailerUrl: "https://www.youtube.com/embed/jZ_yZ5bKq7I",
    tags: ["Gabimaru", "Tao", "MAPPA", "Ninja", "Shinzen"],
    totalUnits: 13,
    unitType: "episodes"
  },
  {
    id: "dororo",
    title: "Dororo",
    originalTitle: "どろろ",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1879/100467.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/u2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.2,
    ratingCount: "1.1M",
    year: 2019,
    ongoing: false,
    runtimeOrChapters: "24 Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Adventure", "Historical", "Supernatural"],
    platformOrStudio: "MAPPA / Tezuka Productions",
    synopsis: "A young samurai whose father sacrificed 48 of his body parts to demons wanders Sengoku-era Japan with prosthetic sword limbs, slaying demons to reclaim what was stolen.",
    quote: "EVERY TIME I SLAY A DEMON, I REGAIN A PIECE OF MY SOUL.",
    rank: "Rank #1 Samurai Revenge",
    membersCount: "1.1M Members",
    trailerUrl: "https://www.youtube.com/embed/4b5E43wJ64w",
    tags: ["Hyakkimaru", "Demons", "Sengoku", "MAPPA", "Swordsman"],
    totalUnits: 24,
    unitType: "episodes"
  },
  {
    id: "samurai-champloo",
    title: "Samurai Champloo",
    originalTitle: "サムライチャンプルー",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1375/121599.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/t2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.5,
    ratingCount: "1.2M",
    year: 2004,
    ongoing: false,
    runtimeOrChapters: "26 Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Adventure", "Historical", "Comedy"],
    platformOrStudio: "Manglobe",
    synopsis: "Fuu, a clumsy waitress, rescues two fierce ronin from execution and convinces them to escort her across Edo Japan in search of 'the samurai who smells of sunflowers'.",
    quote: "HIP-HOP MEETS THE BUSHIDO WAY.",
    rank: "Rank #1 Hip-Hop Samurai",
    membersCount: "1.2M Members",
    trailerUrl: "https://www.youtube.com/embed/Fn39Fz0kUuA",
    tags: ["Mugen", "Jin", "Nujabes", "Hip Hop", "Samurai"],
    totalUnits: 26,
    unitType: "episodes"
  },
  {
    id: "tokyo-ghoul",
    title: "Tokyo Ghoul",
    originalTitle: "東京喰種トーキョーグール",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1498/134443.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/s2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 7.8,
    ratingCount: "2.7M",
    year: 2014,
    ongoing: false,
    runtimeOrChapters: "24 Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Dark Fantasy", "Horror", "Psychological"],
    platformOrStudio: "Studio Pierrot",
    synopsis: "Ken Kaneki barely survives a deadly date with a ghoul and undergoes emergency surgery that transforms him into Tokyo's first half-human, half-ghoul hybrid.",
    quote: "WHAT IS 1000 MINUS 7?",
    rank: "Rank #1 Dark Psychological",
    membersCount: "2.7M Members",
    trailerUrl: "https://www.youtube.com/embed/vGuQeQhUGGU",
    tags: ["Kaneki", "Unravel", "Kagune", "CCG", "Pierrot"],
    totalUnits: 24,
    unitType: "episodes"
  },
  {
    id: "fate-zero",
    title: "Fate/Zero",
    originalTitle: "フェイト/ゼロ",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/2/73249.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/r2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.3,
    ratingCount: "1.4M",
    year: 2011,
    ongoing: false,
    runtimeOrChapters: "25 Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Fantasy", "Supernatural", "Suspense"],
    platformOrStudio: "ufotable",
    synopsis: "Seven mages summon legendary Heroic Spirits to duel to the death in the Fourth Holy Grail War over a relic capable of granting any wish.",
    quote: "THERE IS NO HOPE ON THE BATTLEFIELD.",
    rank: "Rank #1 Battle Royale",
    membersCount: "1.4M Members",
    trailerUrl: "https://www.youtube.com/embed/bXv2Z2v0R2c",
    tags: ["Kiritsugu", "Saber", "Holy Grail", "ufotable", "Tragedy"],
    totalUnits: 25,
    unitType: "episodes"
  },
  {
    id: "your-name",
    title: "Your Name.",
    originalTitle: "君の名は。",
    category: "anime",
    mediaType: "movie",
    coverImage: "https://cdn.myanimelist.net/images/anime/1935/127974.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/q2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.0,
    ratingCount: "2.6M",
    year: 2016,
    ongoing: false,
    runtimeOrChapters: "107 Minutes",
    ageRating: "PG",
    genres: ["Romance", "Drama", "Supernatural", "Award Winning"],
    platformOrStudio: "CoMix Wave Films / Makoto Shinkai",
    synopsis: "Two teenagers share a profound, magical connection upon discovering that they are swapping bodies across space and time before a comet threatens devastation.",
    quote: "TREASURE THE EXPERIENCE. DREAMS FADE AWAY AFTER YOU WAKE UP.",
    rank: "Rank #1 Worldwide Anime Film",
    membersCount: "2.6M Members",
    trailerUrl: "https://www.youtube.com/embed/s0wTdCQoc2k",
    tags: ["Makoto Shinkai", "RADWIMPS", "Body Swap", "Comet", "Tokyo"],
    totalUnits: 1,
    unitType: "episodes"
  },
  {
    id: "a-silent-voice",
    title: "A Silent Voice",
    originalTitle: "聲の形 (Koe no Katachi)",
    category: "anime",
    mediaType: "movie",
    coverImage: "https://cdn.myanimelist.net/images/anime/1122/96481.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/p4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.9,
    ratingCount: "2.3M",
    year: 2016,
    ongoing: false,
    runtimeOrChapters: "130 Minutes",
    ageRating: "PG-13",
    genres: ["Drama", "Award Winning", "School"],
    platformOrStudio: "Kyoto Animation",
    synopsis: "A former elementary school bully seeks redemption from the deaf girl he tormented years ago, learning to listen to the world around him.",
    quote: "I WANT TO HELP YOU LIVE.",
    rank: "Rank #2 Drama Feature",
    membersCount: "2.3M Members",
    trailerUrl: "https://www.youtube.com/embed/nfK6UgLra7g",
    tags: ["Kyoto Animation", "Redemption", "Deaf", "Friendship", "Masterpiece"],
    totalUnits: 1,
    unitType: "episodes"
  },
  {
    id: "spirited-away",
    title: "Spirited Away",
    originalTitle: "千と千尋の神隠し",
    category: "anime",
    mediaType: "movie",
    coverImage: "https://cdn.myanimelist.net/images/anime/9/7581.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/m4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.8,
    ratingCount: "1.9M",
    year: 2001,
    ongoing: false,
    runtimeOrChapters: "125 Minutes",
    ageRating: "PG",
    genres: ["Adventure", "Award Winning", "Supernatural", "Fantasy"],
    platformOrStudio: "Studio Ghibli / Hayao Miyazaki",
    synopsis: "During her family's move to the suburbs, a somber 10-year-old girl wanders into a spirit bathhouse ruled by witches and gods after her parents are transformed into pigs.",
    quote: "ONCE YOU'VE MET SOMEONE YOU NEVER REALLY FORGET THEM.",
    rank: "Oscar Winner Best Animated Feature",
    membersCount: "1.9M Members",
    trailerUrl: "https://www.youtube.com/embed/ByXuk9QqQkk",
    tags: ["Ghibli", "Miyazaki", "Chihiro", "Haku", "Oscar Winner"],
    totalUnits: 1,
    unitType: "episodes"
  },
  {
    id: "princess-mononoke",
    title: "Princess Mononoke",
    originalTitle: "もののけ姫",
    category: "anime",
    mediaType: "movie",
    coverImage: "https://cdn.myanimelist.net/images/anime/7/75810.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/l4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.7,
    ratingCount: "1.2M",
    year: 1997,
    ongoing: false,
    runtimeOrChapters: "134 Minutes",
    ageRating: "PG-13",
    genres: ["Action", "Adventure", "Fantasy"],
    platformOrStudio: "Studio Ghibli / Hayao Miyazaki",
    synopsis: "In search of a cure for a demon's curse, prince Ashitaka finds himself in the middle of a brutal war between the forest gods and an iron-mining settlement.",
    quote: "TO SEE WITH EYES UNCLOUDED BY HATE.",
    rank: "Rank #1 Environmental Epic",
    membersCount: "1.2M Members",
    trailerUrl: "https://www.youtube.com/embed/4OiMOHRDs14",
    tags: ["Ghibli", "Ashitaka", "San", "Nature", "Miyazaki"],
    totalUnits: 1,
    unitType: "episodes"
  },
  {
    id: "akira-movie",
    title: "Akira",
    originalTitle: "AKIRA",
    category: "anime",
    mediaType: "movie",
    coverImage: "https://cdn.myanimelist.net/images/anime/10/75815.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/k4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.2,
    ratingCount: "950K",
    year: 1988,
    ongoing: false,
    runtimeOrChapters: "124 Minutes",
    ageRating: "R",
    genres: ["Action", "Sci-Fi", "Cyberpunk", "Psychological"],
    platformOrStudio: "TMS Entertainment / Katsuhiro Otomo",
    synopsis: "A secret military project endangers Neo-Tokyo when it turns a reckless biker gang member into a rampaging psychic psychopath who can only be stopped by his teenage friend.",
    quote: "KANEDA! TETSUO!",
    rank: "Rank #1 Cyberpunk Blueprint",
    membersCount: "950K Members",
    trailerUrl: "https://www.youtube.com/embed/nA8KmHC2P-g",
    tags: ["Neo Tokyo", "Kaneda", "Cyberpunk", "Bike Slide", "Masterpiece"],
    totalUnits: 1,
    unitType: "episodes"
  },
  {
    id: "psycho-pass",
    title: "Psycho-Pass",
    originalTitle: "PSYCHO-PASS サイコパス",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/5/43399.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/j4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.3,
    ratingCount: "1.6M",
    year: 2012,
    ongoing: false,
    runtimeOrChapters: "22 Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Sci-Fi", "Suspense", "Psychological"],
    platformOrStudio: "Production I.G",
    synopsis: "In a cyberpunk future where human minds are measured by the Sibyl System to determine criminal intent, inspectors and enforcers hunt down those flagged as latent criminals.",
    quote: "THE LAW DOESN'T PROTECT PEOPLE. PEOPLE PROTECT THE LAW.",
    rank: "Rank #1 Dystopian Crime",
    membersCount: "1.6M Members",
    trailerUrl: "https://www.youtube.com/embed/5U_w2s78V1w",
    tags: ["Dominator", "Sibyl System", "Akane", "Kogami", "Production IG"],
    totalUnits: 22,
    unitType: "episodes"
  },
  {
    id: "dorohedoro",
    title: "Dorohedoro",
    originalTitle: "ドロヘドロ",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1483/105401.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/h4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.0,
    ratingCount: "580K",
    year: 2020,
    ongoing: true,
    runtimeOrChapters: "12 Episodes",
    ageRating: "TV-MA",
    genres: ["Action", "Comedy", "Fantasy", "Horror"],
    platformOrStudio: "MAPPA",
    synopsis: "A reptilian-headed amnesiac named Caiman hunts down sorcerers in the grimy city of the Hole to find the one who cursed his face.",
    quote: "THAT IS DOROHEDORO.",
    rank: "Rank #1 Gritty Dark Comedy",
    membersCount: "580K Members",
    trailerUrl: "https://www.youtube.com/embed/rV3dE5G_f7o",
    tags: ["Caiman", "Nikaido", "Gyoza", "MAPPA", "Sorcery"],
    totalUnits: 12,
    unitType: "episodes"
  },
  {
    id: "classroom-of-the-elite",
    title: "Classroom of the Elite",
    originalTitle: "ようこそ実力至上主義の教室へ",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1024/120960.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/g4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 7.9,
    ratingCount: "1.4M",
    year: 2017,
    ongoing: true,
    runtimeOrChapters: "38 Episodes",
    ageRating: "TV-14",
    genres: ["Drama", "Psychological", "School"],
    platformOrStudio: "Lerche",
    synopsis: "At Tokyo Metropolitan Advanced Nurturing High School, student Kiyotaka Ayanokoji manipulates class politics from the shadows while concealing his apex intellect.",
    quote: "ALL PEOPLE ARE NOTHING MORE THAN TOOLS.",
    rank: "Rank #1 School Mind Games",
    membersCount: "1.4M Members",
    trailerUrl: "https://www.youtube.com/embed/o_bZ1L5W9hM",
    tags: ["Ayanokoji", "Class D", "Mind Games", "Lerche", "Psychological"],
    totalUnits: 38,
    unitType: "episodes"
  },
  {
    id: "black-clover",
    title: "Black Clover",
    originalTitle: "ブラッククローバー",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/2/88336.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/f4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 7.9,
    ratingCount: "1.8M",
    year: 2017,
    ongoing: true,
    runtimeOrChapters: "170 Episodes",
    ageRating: "TV-14",
    genres: ["Action", "Comedy", "Fantasy", "Shonen"],
    platformOrStudio: "Studio Pierrot",
    synopsis: "Born with zero magic in a world where magic is everything, Asta receives a mysterious five-leaf grimoire imbued with anti-magic and aims to become the Wizard King.",
    quote: "MY MAGIC IS NEVER GIVING UP!",
    rank: "Rank #3 Long-Running Shonen",
    membersCount: "1.8M Members",
    trailerUrl: "https://www.youtube.com/embed/Q3vP0yQ5R7U",
    tags: ["Asta", "Anti-Magic", "Black Bulls", "Wizard King", "Pierrot"],
    totalUnits: 170,
    unitType: "episodes"
  },
  {
    id: "trigun-stampede",
    title: "Trigun Stampede",
    originalTitle: "TRIGUN STAMPEDE",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1233/131495.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/e4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 7.9,
    ratingCount: "250K",
    year: 2023,
    ongoing: true,
    runtimeOrChapters: "12 Episodes",
    ageRating: "TV-14",
    genres: ["Action", "Sci-Fi", "Space Western"],
    platformOrStudio: "Orange",
    synopsis: "On the desert planet of No Man's Land, pacifist gunslinger Vash the Stampede runs from bounty hunters while trying to stop his twin brother Knives from destroying humanity.",
    quote: "LOVE AND PEACE!",
    rank: "Rank #1 3D CGI Direction",
    membersCount: "250K Members",
    trailerUrl: "https://www.youtube.com/embed/5a4G1E_s9u4",
    tags: ["Vash", "Studio Orange", "Space Western", "CGI", "Knives"],
    totalUnits: 12,
    unitType: "episodes"
  },
  {
    id: "jujutsu-kaisen-0",
    title: "Jujutsu Kaisen 0: The Movie",
    originalTitle: "劇場版 呪術廻戦 0",
    category: "anime",
    mediaType: "movie",
    coverImage: "https://cdn.myanimelist.net/images/anime/1121/119044.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/d4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.5,
    ratingCount: "1.2M",
    year: 2021,
    ongoing: false,
    runtimeOrChapters: "105 Minutes",
    ageRating: "PG-13",
    genres: ["Action", "Fantasy", "Supernatural"],
    platformOrStudio: "MAPPA",
    synopsis: "Yuta Okkotsu is enrolled at Tokyo Jujutsu High by Satoru Gojo after his childhood friend Rika manifests as a monstrous cursed spirit attached to him.",
    quote: "WE ARE LOVE IN ITS PUREST CURSED FORM.",
    rank: "Rank #1 Shonen Prequel Film",
    membersCount: "1.2M Members",
    trailerUrl: "https://www.youtube.com/embed/2docezZl574",
    tags: ["Yuta", "Rika", "Gojo", "Geto", "MAPPA"],
    totalUnits: 1,
    unitType: "episodes"
  },
  {
    id: "dr-stone",
    title: "Dr. STONE",
    originalTitle: "ドクターストーン",
    category: "anime",
    mediaType: "anime",
    coverImage: "https://cdn.myanimelist.net/images/anime/1613/102576.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/c4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.3,
    ratingCount: "1.7M",
    year: 2019,
    ongoing: true,
    runtimeOrChapters: "58 Episodes",
    ageRating: "TV-14",
    genres: ["Adventure", "Sci-Fi", "Comedy", "Shonen"],
    platformOrStudio: "TMS Entertainment",
    synopsis: "After all of humanity is mysteriously turned to stone for thousands of years, high school science prodigy Senku Ishigami awakens to rebuild human civilization from scratch with science.",
    quote: "GET EXCITED! THIS IS TEN BILLION PERCENT SCIENCE!",
    rank: "Rank #1 Hard Science Shonen",
    membersCount: "1.7M Members",
    trailerUrl: "https://www.youtube.com/embed/3z5eG9_7W1U",
    tags: ["Senku", "Science", "Kingdom of Science", "Stone Age", "TMS"],
    totalUnits: 58,
    unitType: "episodes"
  }
];
