module.exports = {
  comics: [
    {
      id: "batman-year-one",
      title: "Batman: Year One",
      originalTitle: "Batman: Year One",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/hkBaDkMWbLaf8B1r5vsIRqqXqvm.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      rating: 9.3,
      ratingCount: "850K",
      year: 1987,
      ongoing: false,
      runtimeOrChapters: "4 Issues (#404-407)",
      ageRating: "Teen+",
      genres: ["Superhero", "Noir", "Crime"],
      platformOrStudio: "DC Comics / Frank Miller & David Mazzucchelli",
      synopsis: "Bruce Wayne returns to Gotham City after 12 years abroad to wage a personal war on crime as Lieutenant James Gordon arrives to confront corrupt police officials.",
      quote: "LADIES. GENTLEMEN. YOU HAVE EATEN WELL. FROM THIS MOMENT ON... NONE OF YOU ARE SAFE.",
      rank: "Rank #1 Definitive Batman Origin",
      membersCount: "850K Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      featured: true,
      tags: ["Batman", "Jim Gordon", "Frank Miller", "Gotham", "Noir"],
      totalUnits: 4,
      unitType: "chapters"
    },
    {
      id: "batman-the-dark-knight-returns",
      title: "The Dark Knight Returns",
      originalTitle: "The Dark Knight Returns",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/sAtoMqDVhNDQBc3QJL3RF6hlxGq.jpg",
      rating: 9.4,
      ratingCount: "980K",
      year: 1986,
      ongoing: false,
      runtimeOrChapters: "4 Prestige Issues",
      ageRating: "Mature",
      genres: ["Superhero", "Dystopian", "Political"],
      platformOrStudio: "DC Comics / Frank Miller",
      synopsis: "A 55-year-old Bruce Wayne comes out of retirement in a dystopian future Gotham overrun by mutant gangs, confronting Two-Face, the Joker, and ultimately the President's enforcer: Superman.",
      quote: "I WANT YOU TO REMEMBER THE ONE MAN WHO BEAT YOU.",
      rank: "Rank #1 Graphic Novel Masterpiece",
      membersCount: "980K Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      featured: true,
      trending: true,
      tags: ["Frank Miller", "Superman vs Batman", "Mutant Gang", "Dystopia"],
      totalUnits: 4,
      unitType: "chapters"
    },
    {
      id: "batman-the-killing-joke",
      title: "Batman: The Killing Joke",
      originalTitle: "Batman: The Killing Joke",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1r5vsIRqqXqvm.jpg",
      rating: 9.2,
      ratingCount: "1.2M",
      year: 1988,
      ongoing: false,
      runtimeOrChapters: "One-Shot Graphic Novel",
      ageRating: "Mature",
      genres: ["Psychological", "Crime", "Superhero"],
      platformOrStudio: "DC Comics / Alan Moore & Brian Bolland",
      synopsis: "The Joker escapes Arkham Asylum and shoots Barbara Gordon in an insidious psychological experiment to prove to Batman that all it takes is one bad day to reduce the sanest man alive to lunacy.",
      quote: "ALL IT TAKES IS ONE BAD DAY TO REDUCE THE SANEST MAN ALIVE TO LUNACY.",
      rank: "Rank #1 Joker Graphic Novel",
      membersCount: "1.2M Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Alan Moore", "Joker", "Brian Bolland", "One Bad Day", "Arkham"],
      totalUnits: 1,
      unitType: "chapters"
    },
    {
      id: "all-star-superman",
      title: "All-Star Superman",
      originalTitle: "All-Star Superman",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/7d6woWBsig1VvMN9gyOkGTTLHf2.jpg",
      rating: 9.5,
      ratingCount: "750K",
      year: 2005,
      ongoing: false,
      runtimeOrChapters: "12 Issues",
      ageRating: "All Ages",
      genres: ["Superhero", "Sci-Fi", "Philosophical"],
      platformOrStudio: "DC Comics / Grant Morrison & Frank Quitely",
      synopsis: "Dying of solar radiation poisoning, Superman embarks on his final twelve labors to ensure the survival and inspiration of humanity before his life ends.",
      quote: "YOU'RE MUCH STRONGER THAN YOU THINK YOU ARE. TRUST ME.",
      rank: "Rank #1 Greatest Superman Comic Ever Written",
      membersCount: "750K Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Grant Morrison", "Frank Quitely", "Superman", "Solar", "Hope"],
      totalUnits: 12,
      unitType: "chapters"
    },
    {
      id: "kingdom-come-dc",
      title: "Kingdom Come",
      originalTitle: "Kingdom Come",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      rating: 9.4,
      ratingCount: "680K",
      year: 1996,
      ongoing: false,
      runtimeOrChapters: "4 Prestige Issues",
      ageRating: "Teen+",
      genres: ["Superhero", "Epic", "Painted Art"],
      platformOrStudio: "DC Comics / Mark Waid & Alex Ross",
      synopsis: "In a future where a reckless generation of anti-heroes causes mass destruction, an aged Superman steps out of exile to reform the Justice League, leading to an apocalyptic battle.",
      quote: "TRUTH AND JUSTICE ARE NOT FADS.",
      rank: "Rank #1 Painted Comic Masterpiece",
      membersCount: "680K Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Alex Ross", "Mark Waid", "Justice League", "Painted", "Apocalypse"],
      totalUnits: 4,
      unitType: "chapters"
    },
    {
      id: "saga-comic",
      title: "Saga",
      originalTitle: "Saga",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/w3LxiVYPqrlxqP9Yue483o20BpB.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/70Aptmsy688gKjO5Pq91P7kS04A.jpg",
      rating: 9.6,
      ratingCount: "890K",
      year: 2012,
      ongoing: true,
      runtimeOrChapters: "66+ Issues",
      ageRating: "Mature",
      genres: ["Space Opera", "Fantasy", "Drama"],
      platformOrStudio: "Image Comics / Brian K. Vaughan & Fiona Staples",
      synopsis: "Two soldiers from opposite sides of a galactic war between horns and wings fall in love and risk everything to bring their newborn daughter Hazel safely through an unforgiving universe.",
      quote: "THIS IS HOW AN IDEA DIES.",
      rank: "Multiple Eisner Award Winner",
      membersCount: "890K Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      featured: true,
      tags: ["Brian K Vaughan", "Fiona Staples", "Image Comics", "Space Opera", "Hazel"],
      totalUnits: 66,
      unitType: "chapters"
    },
    {
      id: "invincible-comic",
      title: "Invincible (Comics)",
      originalTitle: "Invincible",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
      rating: 9.4,
      ratingCount: "920K",
      year: 2003,
      ongoing: false,
      runtimeOrChapters: "144 Issues (Complete)",
      ageRating: "Mature",
      genres: ["Superhero", "Action", "Gore", "Sci-Fi"],
      platformOrStudio: "Image Comics / Skybound / Robert Kirkman",
      synopsis: "Mark Grayson inherits the immense superpowers of his alien father Omni-Man, only to discover a universe-spanning empire of ruthless conquerors headed for Earth.",
      quote: "I'D STILL HAVE YOU, DAD.",
      rank: "Rank #1 Modern Indie Superhero Comic",
      membersCount: "920K Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Omni-Man", "Mark Grayson", "Viltrumites", "Robert Kirkman", "Ryan Ottley"],
      totalUnits: 144,
      unitType: "chapters"
    },
    {
      id: "civil-war-marvel",
      title: "Civil War (Marvel)",
      originalTitle: "Civil War",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/bOGkgRGdhrBYJSLv7KiTe9Bhbx0.jpg",
      rating: 9.0,
      ratingCount: "1.4M",
      year: 2006,
      ongoing: false,
      runtimeOrChapters: "7 Core Issues + Tie-ins",
      ageRating: "Teen+",
      genres: ["Superhero", "Political", "Action"],
      platformOrStudio: "Marvel Comics / Mark Millar & Steve McNiven",
      synopsis: "A superhero tragedy in Stamford prompts the U.S. government to pass the Superhuman Registration Act, splintering the superhero community into opposing factions led by Iron Man and Captain America.",
      quote: "WHOSE SIDE ARE YOU ON?",
      rank: "Rank #1 Marvel Event of the 2000s",
      membersCount: "1.4M Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Iron Man", "Captain America", "Mark Millar", "Spider-Man Unmasked", "Marvel"],
      totalUnits: 7,
      unitType: "chapters"
    },
    {
      id: "daredevil-born-again",
      title: "Daredevil: Born Again",
      originalTitle: "Daredevil: Born Again",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/QWbPaDxiB6LW2vdaDr7MBlR12W.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/7eHn2P5Z0m2P1V6E4L2U9m8N7x1.jpg",
      rating: 9.5,
      ratingCount: "580K",
      year: 1986,
      ongoing: false,
      runtimeOrChapters: "7 Issues (#227-233)",
      ageRating: "Mature",
      genres: ["Superhero", "Crime", "Drama"],
      platformOrStudio: "Marvel Comics / Frank Miller & David Mazzucchelli",
      synopsis: "Karen Page sells Matt Murdock's secret identity for a drug fix, prompting the Kingpin to systematically destroy Matt's career, home, and sanity before Daredevil is spiritually reborn.",
      quote: "A MAN WITHOUT HOPE IS A MAN WITHOUT FEAR.",
      rank: "Rank #1 Greatest Marvel Storyline",
      membersCount: "580K Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Matt Murdock", "Kingpin", "Frank Miller", "Nuke", "Hell's Kitchen"],
      totalUnits: 7,
      unitType: "chapters"
    },
    {
      id: "house-of-x-powers-of-x",
      title: "House of X / Powers of X",
      originalTitle: "House of X / Powers of X",
      category: "comics",
      mediaType: "comic",
      coverImage: "https://image.tmdb.org/t/p/w780/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
      rating: 9.3,
      ratingCount: "620K",
      year: 2019,
      ongoing: false,
      runtimeOrChapters: "12 Interleaved Issues",
      ageRating: "Teen+",
      genres: ["Superhero", "Sci-Fi", "Political"],
      platformOrStudio: "Marvel Comics / Jonathan Hickman & Pepe Larraz",
      synopsis: "Jonathan Hickman revolutionizes the mutant mythos as Charles Xavier, Magneto, and Moira MacTaggert establish a sovereign mutant nation on the living island of Krakoa with resurrection protocols.",
      quote: "WHILE YOU SLEPT, THE WORLD CHANGED.",
      rank: "Rank #1 Modern X-Men Masterpiece",
      membersCount: "620K Readers",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Krakoa", "Hickman", "Moira X", "Resurrection", "Mutants"],
      totalUnits: 12,
      unitType: "chapters"
    }
  ],
  kpop: [
    {
      id: "stray-kids-5-star",
      title: "Stray Kids: 5-STAR",
      originalTitle: "★★★★★ (5-STAR)",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
      rating: 9.4,
      ratingCount: "1.9M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "12 Tracks (Full Album)",
      ageRating: "All Ages",
      genres: ["K-Pop", "Hip-Hop", "EDM", "Self-Produced"],
      platformOrStudio: "JYP Entertainment / Republic Records",
      synopsis: "The chart-topping 3rd full album by Stray Kids, featuring global smash hit 'S-Class', produced in-house by 3RACHA (Bang Chan, Changbin, Han) blending traditional Korean pansori with drill beats.",
      quote: "WE ARE FIVE STARS SPECIAL!",
      rank: "Billboard 200 #1 Album",
      membersCount: "1.9M Fans",
      trailerUrl: "https://www.youtube.com/embed/JsOOis4bBFg",
      featured: true,
      trending: true,
      tags: ["3RACHA", "S-Class", "Felix", "Bang Chan", "Billboard #1"],
      totalUnits: 12,
      unitType: "tracks"
    },
    {
      id: "seventeen-fml",
      title: "SEVENTEEN: FML",
      originalTitle: "10th Mini Album 'FML'",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/eeijXm355vAUtq5lgwp2QIY9R62.jpg",
      rating: 9.5,
      ratingCount: "2.1M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "6 Tracks",
      ageRating: "All Ages",
      genres: ["K-Pop", "Dance", "Hip-Hop", "Performance"],
      platformOrStudio: "PLEDIS Entertainment / HYBE",
      synopsis: "The historic multi-million selling album featuring double title tracks 'Super' (Sonogong) and 'F*ck My Life', self-produced by Woozi and featuring SEVENTEEN's world-renowned 13-member synchronization.",
      quote: "DARUMDARIMDA, LIKE SON OGONG!",
      rank: "IFPI Best Selling Album Globally 2023 (6M+ Copies)",
      membersCount: "2.1M Fans",
      trailerUrl: "https://www.youtube.com/embed/-GQg25oP0S4",
      featured: true,
      trending: true,
      tags: ["Woozi", "Super", "Sonogong", "Carats", "Synchronized"],
      totalUnits: 6,
      unitType: "tracks"
    },
    {
      id: "ateez-the-world-will",
      title: "ATEEZ: THE WORLD EP.FIN : WILL",
      originalTitle: "THE WORLD EP.FIN : WILL",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/gL0bU9a0Z1N6X8k3P2q8V1x9yP.jpg",
      rating: 9.3,
      ratingCount: "1.4M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "12 Tracks",
      ageRating: "All Ages",
      genres: ["K-Pop", "Cyberpunk", "Hip-Hop", "Rock"],
      platformOrStudio: "KQ Entertainment",
      synopsis: "The climax of ATEEZ's cinematic sci-fi rebellion saga featuring the hard-hitting title track 'Crazy Form' and unit songs, achieving Billboard 200 #1 with anarchic pirate energy.",
      quote: "MY STYLE IS CRAZY FORM!",
      rank: "Billboard 200 #1 Debut",
      membersCount: "1.4M Fans",
      trailerUrl: "https://www.youtube.com/embed/g2g6Kj4B6Fw",
      tags: ["Hongjoong", "San", "Crazy Form", "Pirates", "KQ"],
      totalUnits: 12,
      unitType: "tracks"
    },
    {
      id: "txt-temptation",
      title: "TXT: The Name Chapter: TEMPTATION",
      originalTitle: "이름의 장: TEMPTATION",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
      rating: 9.2,
      ratingCount: "1.5M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "5 Tracks",
      ageRating: "All Ages",
      genres: ["K-Pop", "Afrobeats", "Dream Pop", "Alt Rock"],
      platformOrStudio: "BIGHIT MUSIC / HYBE",
      synopsis: "TOMORROW X TOGETHER's critically acclaimed conceptual masterpiece chronicling the temptation of Peter Pan's Neverland with viral title track 'Sugar Rush Ride'.",
      quote: "THE DEVIL SAID, GIMME MORE.",
      rank: "Billboard 200 #1 Album",
      membersCount: "1.5M Fans",
      trailerUrl: "https://www.youtube.com/embed/P9tKTxbgdkk",
      tags: ["Yeonjun", "Soobin", "Sugar Rush Ride", "Peter Pan", "BigHit"],
      totalUnits: 5,
      unitType: "tracks"
    },
    {
      id: "enhypen-dark-blood",
      title: "ENHYPEN: DARK BLOOD",
      originalTitle: "DARK BLOOD",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/suaEOtk1916guMe7qdZKi4LnIQf.jpg",
      rating: 9.3,
      ratingCount: "1.3M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "6 Tracks",
      ageRating: "All Ages",
      genres: ["K-Pop", "R&B", "Dark Fantasy", "Pop"],
      platformOrStudio: "BELIFT LAB / HYBE",
      synopsis: "ENHYPEN's signature dark vampire romantic fantasy concept album featuring the seductive R&B lead single 'Bite Me' with choreographed partner dance routines.",
      quote: "JUST COME KISS ME AND BITE ME.",
      rank: "Rank #1 Dark Vampire Concept",
      membersCount: "1.3M Fans",
      trailerUrl: "https://www.youtube.com/embed/wXFLzODIdUI",
      tags: ["Vampire Lore", "Bite Me", "Heeseung", "Sunghoon", "Belift Lab"],
      totalUnits: 6,
      unitType: "tracks"
    },
    {
      id: "aespa-armageddon",
      title: "aespa: Armageddon - The 1st Album",
      originalTitle: "Armageddon",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
      rating: 9.5,
      ratingCount: "1.8M",
      year: 2024,
      ongoing: false,
      runtimeOrChapters: "10 Tracks",
      ageRating: "All Ages",
      genres: ["K-Pop", "Hyperpop", "Cyberpunk", "Hip-Hop"],
      platformOrStudio: "SM Entertainment",
      synopsis: "aespa's historic full-length debut featuring the seismic double-punch of 'Supernova' and 'Armageddon', dominating charts with hyper-futuristic metaverse and multiverse lore.",
      quote: "SU-SU-SU-SUPERNOVA!",
      rank: "All-Kill #1 Across Korean Music Charts",
      membersCount: "1.8M Fans",
      trailerUrl: "https://www.youtube.com/embed/phuiiNCxRMg",
      featured: true,
      trending: true,
      tags: ["Supernova", "Karina", "Winter", "SM Entertainment", "Hyperpop"],
      totalUnits: 10,
      unitType: "tracks"
    },
    {
      id: "le-sserafim-unforgiven",
      title: "LE SSERAFIM: UNFORGIVEN",
      originalTitle: "UNFORGIVEN",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
      rating: 9.1,
      ratingCount: "1.7M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "13 Tracks",
      ageRating: "All Ages",
      genres: ["K-Pop", "Western", "Dance", "Hip-Hop"],
      platformOrStudio: "SOURCE MUSIC / HYBE",
      synopsis: "LE SSERAFIM's defiant 1st studio album, sampling Ennio Morricone's 'The Good, the Bad and the Ugly' featuring Nile Rodgers on guitar, celebrating fearlessness and self-worth.",
      quote: "UNFORGIVEN, I'M A VILLAIN, I'M A CLOWN.",
      rank: "Rank #1 Fearless Concept",
      membersCount: "1.7M Fans",
      trailerUrl: "https://www.youtube.com/embed/UBURTj20HXI",
      tags: ["Chaewon", "Yunjin", "Kazuha", "Nile Rodgers", "Source Music"],
      totalUnits: 13,
      unitType: "tracks"
    },
    {
      id: "ive-ive-mine",
      title: "IVE: I'VE MINE",
      originalTitle: "I'VE MINE",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/bckxAAq9HPoEO7KLznP04pH38Q1.jpg",
      rating: 9.0,
      ratingCount: "1.5M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "6 Tracks",
      ageRating: "All Ages",
      genres: ["K-Pop", "Dance-Pop", "Sophisti-Pop"],
      platformOrStudio: "Starship Entertainment",
      synopsis: "The triple-title EP exploring self-confidence from diverse perspectives through 'Baddie', 'Off The Record', and 'Either Way', led by cultural icon Jang Won-young.",
      quote: "I'M A BADDIE, B-B-BADDIE.",
      rank: "Triple Million Seller Group",
      membersCount: "1.5M Fans",
      trailerUrl: "https://www.youtube.com/embed/Da40MWUv53g",
      tags: ["Wonyoung", "An Yujin", "Baddie", "Starship", "Chaebol Aesthetic"],
      totalUnits: 6,
      unitType: "tracks"
    },
    {
      id: "twice-ready-to-be",
      title: "TWICE: READY TO BE",
      originalTitle: "READY TO BE",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      rating: 9.2,
      ratingCount: "2.4M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "7 Tracks",
      ageRating: "All Ages",
      genres: ["K-Pop", "Disco Pop", "Dance"],
      platformOrStudio: "JYP Entertainment / Republic Records",
      synopsis: "TWICE's bold 12th mini album featuring 'SET ME FREE' and 'MOONLIGHT SUNRISE', propelling the legendary girl group to headline sold-out stadium tours across the globe.",
      quote: "NO RULES, NO LIMITS, READY TO BE!",
      rank: "First K-Pop Girl Group to Sell Out SoFi Stadium",
      membersCount: "2.4M Fans",
      trailerUrl: "https://www.youtube.com/embed/w4cTYnOPdNk",
      tags: ["TWICE", "Nayeon", "Jihyo", "Stadium Tour", "JYP"],
      totalUnits: 7,
      unitType: "tracks"
    },
    {
      id: "bts-map-of-the-soul-7",
      title: "BTS: Map of the Soul: 7",
      originalTitle: "MAP OF THE SOUL : 7",
      category: "k-pop",
      mediaType: "k-pop",
      coverImage: "https://image.tmdb.org/t/p/w780/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
      rating: 9.8,
      ratingCount: "5.5M",
      year: 2020,
      ongoing: false,
      runtimeOrChapters: "20 Tracks",
      ageRating: "All Ages",
      genres: ["K-Pop", "Hip-Hop", "R&B", "Pop"],
      platformOrStudio: "BIGHIT MUSIC / HYBE",
      synopsis: "BTS's monumental 4th studio album looking back on seven years together as a group through Jungian psychoanalysis, featuring the kinetic anthem 'ON' and 'Black Swan'.",
      quote: "BRING THE PAIN ON!",
      rank: "Best Selling Album in South Korean History (5M+ Copies)",
      membersCount: "5.5M Fans",
      trailerUrl: "https://www.youtube.com/embed/mPVDGOVjRQ0",
      featured: true,
      tags: ["BTS", "RM", "Jungkook", "Jimin", "Black Swan", "ARMY"],
      totalUnits: 20,
      unitType: "tracks"
    }
  ]
};
