module.exports = [
  {
    id: "the-witcher-3",
    title: "The Witcher 3: Wild Hunt",
    originalTitle: "Wiedźmin 3: Dziki Gon",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/yQxGv61nFqZ0nL0uF306b9qC0oT.jpg",
    rating: 9.6,
    ratingCount: "1.8M",
    year: 2015,
    ongoing: false,
    runtimeOrChapters: "150+ Hours",
    ageRating: "M - Mature 17+",
    genres: ["RPG", "Open World", "Dark Fantasy", "Story-Rich"],
    platformOrStudio: "CD PROJEKT RED",
    synopsis: "Monster hunter Geralt of Rivia tracks down Ciri, the Child of Prophecy, across the war-ravaged continent of the Northern Realms while pursued by the spectral cavalcade known as the Wild Hunt.",
    quote: "EVIL IS EVIL. LESSER, GREATER, MIDDLING... MAKES NO DIFFERENCE.",
    rank: "Game of the Decade Winner",
    membersCount: "1.8M Players",
    trailerUrl: "https://www.youtube.com/embed/c0i88t0Kacs",
    featured: true,
    trending: true,
    tags: ["Geralt", "Ciri", "CDPR", "Open World", "Bloody Baron"],
    totalUnits: 150,
    unitType: "hours"
  },
  {
    id: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    originalTitle: "Red Dead Redemption 2",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/p4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.7,
    ratingCount: "2.1M",
    year: 2018,
    ongoing: false,
    runtimeOrChapters: "120+ Hours",
    ageRating: "M - Mature 17+",
    genres: ["Action", "Open World", "Western", "Story-Rich"],
    platformOrStudio: "Rockstar Games",
    synopsis: "Arthur Morgan and the Van der Linde gang flee across the rugged American frontier at the dawn of the 20th century, wrestling with loyalty, modernization, and redemption.",
    quote: "I GAVE YOU ALL I HAD. I DID.",
    rank: "Rank #1 Storytelling in Gaming",
    membersCount: "2.1M Players",
    trailerUrl: "https://www.youtube.com/embed/eaW0tYpxyp0",
    featured: true,
    trending: true,
    tags: ["Arthur Morgan", "Dutch", "Rockstar", "Western", "Masterpiece"],
    totalUnits: 120,
    unitType: "hours"
  },
  {
    id: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    originalTitle: "Baldur's Gate 3",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/gmECX1DvE9RiTeiKVPV7ndJTX8o.jpg",
    rating: 9.6,
    ratingCount: "1.4M",
    year: 2023,
    ongoing: false,
    runtimeOrChapters: "140+ Hours",
    ageRating: "M - Mature 17+",
    genres: ["CRPG", "Fantasy", "Turn-Based", "Choices Matter"],
    platformOrStudio: "Larian Studios",
    synopsis: "Abducted by Mind Flayers and infected with an illithid tadpole, you and an eccentric cast of companions resist the creeping transformation while unravelling a plot by the Absolute.",
    quote: "AUTHORITY.",
    rank: "Game of the Year 2023",
    membersCount: "1.4M Players",
    trailerUrl: "https://www.youtube.com/embed/OcP0WdH7rTs",
    featured: true,
    tags: ["D&D", "Larian", "Astarion", "Mind Flayer", "Turn-Based"],
    totalUnits: 140,
    unitType: "hours"
  },
  {
    id: "zelda-breath-of-the-wild",
    title: "The Legend of Zelda: Breath of the Wild",
    originalTitle: "ゼルダの伝説 ブレス オブ ザ ワイルド",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://image.tmdb.org/t/p/w780/k4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/q2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.7,
    ratingCount: "2.4M",
    year: 2017,
    ongoing: false,
    runtimeOrChapters: "100+ Hours",
    ageRating: "E10+",
    genres: ["Action", "Adventure", "Open World", "Fantasy"],
    platformOrStudio: "Nintendo EPD",
    synopsis: "Link awakens from a century-long slumber without memories to discover Hyrule in ruins, embarking on a peerless physics-driven journey of survival to conquer Calamity Ganon.",
    quote: "OPEN YOUR EYES.",
    rank: "Game of the Year 2017",
    membersCount: "2.4M Players",
    trailerUrl: "https://www.youtube.com/embed/zw47_q9wbBE",
    tags: ["Link", "Zelda", "Nintendo", "Hyrule", "Physics"],
    totalUnits: 100,
    unitType: "hours"
  },
  {
    id: "zelda-tears-of-the-kingdom",
    title: "The Legend of Zelda: Tears of the Kingdom",
    originalTitle: "ゼルダの伝説 ティアーズ オブ ザ キングダム",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://image.tmdb.org/t/p/w780/j4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/5n2P0F537K8Nl559Z9W3UvE3k2N.jpg",
    rating: 9.6,
    ratingCount: "1.9M",
    year: 2023,
    ongoing: false,
    runtimeOrChapters: "120+ Hours",
    ageRating: "E10+",
    genres: ["Action", "Adventure", "Open World", "Sandbox"],
    platformOrStudio: "Nintendo EPD",
    synopsis: "Link takes to the floating sky islands and subterranean depths of Hyrule, armed with Ultrahand creation powers to forge contraptions and solve the mystery of the Upheaval.",
    quote: "FIND ME, LINK.",
    rank: "Rank #1 Sandbox Engineering",
    membersCount: "1.9M Players",
    trailerUrl: "https://www.youtube.com/embed/uHGShqcAHlQ",
    tags: ["Ultrahand", "Sky Islands", "Depths", "Ganondorf", "Nintendo"],
    totalUnits: 120,
    unitType: "hours"
  },
  {
    id: "god-of-war-2018",
    title: "God of War (2018)",
    originalTitle: "God of War",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/tC3P1K9n7q8E2m5N4X6p8V1x9yP.jpg",
    rating: 9.5,
    ratingCount: "2.3M",
    year: 2018,
    ongoing: false,
    runtimeOrChapters: "40 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Action", "Adventure", "Mythology", "Cinematic"],
    platformOrStudio: "Santa Monica Studio / PlayStation",
    synopsis: "Living as a man in the realm of Norse gods and monsters, Kratos and his son Atreus venture to the highest peak in the nine realms to scatter Faye's ashes.",
    quote: "BOY.",
    rank: "Game of the Year 2018",
    membersCount: "2.3M Players",
    trailerUrl: "https://www.youtube.com/embed/K0u_kAWLJOA",
    tags: ["Kratos", "Atreus", "Leviathan Axe", "Norse", "PlayStation"],
    totalUnits: 40,
    unitType: "hours"
  },
  {
    id: "god-of-war-ragnarok",
    title: "God of War Ragnarök",
    originalTitle: "God of War Ragnarök",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://image.tmdb.org/t/p/w780/p2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/r2Vq7M6Q9Y2K6N8V1X9Z3p4b8U5.jpg",
    rating: 9.4,
    ratingCount: "1.7M",
    year: 2022,
    ongoing: false,
    runtimeOrChapters: "50 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Action", "Adventure", "Mythology", "Cinematic"],
    platformOrStudio: "Santa Monica Studio / PlayStation",
    synopsis: "Fimbulwinter grips Midgard as Kratos and Atreus travel through each of the Nine Realms, choosing between their own safety and the fate of the cosmos as Ragnarök looms.",
    quote: "WE MUST BE BETTER.",
    rank: "Rank #1 Norse Climax",
    membersCount: "1.7M Players",
    trailerUrl: "https://www.youtube.com/embed/hfJ4Km46A-0",
    tags: ["Thor", "Odin", "Ragnarok", "Kratos", "Valhalla"],
    totalUnits: 50,
    unitType: "hours"
  },
  {
    id: "the-last-of-us-part-1-game",
    title: "The Last of Us Part I",
    originalTitle: "The Last of Us Part I",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1888930/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/uCu4jN6r2F5pT5L7cQ7z0m0z0bE.jpg",
    rating: 9.6,
    ratingCount: "2.8M",
    year: 2013,
    ongoing: false,
    runtimeOrChapters: "20 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Action", "Post-Apocalyptic", "Stealth", "Story-Rich"],
    platformOrStudio: "Naughty Dog / PlayStation",
    synopsis: "In a ravaged civilization overrun by fungal infected, hardened smuggler Joel is hired to smuggle 14-year-old Ellie across a treacherous quarantine quarantine-torn America.",
    quote: "ENDURE AND SURVIVE.",
    rank: "Rank #1 Cinematic Narrative",
    membersCount: "2.8M Players",
    trailerUrl: "https://www.youtube.com/embed/W01L70IGBgE",
    tags: ["Joel", "Ellie", "Clickers", "Naughty Dog", "Masterpiece"],
    totalUnits: 20,
    unitType: "hours"
  },
  {
    id: "the-last-of-us-part-2-game",
    title: "The Last of Us Part II",
    originalTitle: "The Last of Us Part II",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://image.tmdb.org/t/p/w780/d9Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/vFlq03Xl3gJ5vB8k9M1P4E2m3X8.jpg",
    rating: 9.2,
    ratingCount: "1.9M",
    year: 2020,
    ongoing: false,
    runtimeOrChapters: "30 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Action", "Drama", "Stealth", "Survival Horror"],
    platformOrStudio: "Naughty Dog / PlayStation",
    synopsis: "Following a traumatic event in Jackson, Ellie embarks on a relentless cycle of vengeance across the rainy ruins of Seattle, forced to confront the emotional aftermath of her actions.",
    quote: "IF I EVER WERE TO LOSE YOU, I'D SURELY LOSE MYSELF.",
    rank: "Game of the Year 2020",
    membersCount: "1.9M Players",
    trailerUrl: "https://www.youtube.com/embed/vhII1qlcZ4E",
    tags: ["Ellie", "Abby", "Seattle", "Revenge", "Naughty Dog"],
    totalUnits: 30,
    unitType: "hours"
  },
  {
    id: "ghost-of-tsushima",
    title: "Ghost of Tsushima",
    originalTitle: "Ghost of Tsushima",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/7eHn2P5Z0m2P1V6E4L2U9m8N7x1.jpg",
    rating: 9.3,
    ratingCount: "1.6M",
    year: 2020,
    ongoing: false,
    runtimeOrChapters: "50 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Action", "Open World", "Historical", "Stealth"],
    platformOrStudio: "Sucker Punch / PlayStation",
    synopsis: "In 1274, Mongol invaders overwhelm Tsushima Island. Samurai Jin Sakai must cast aside the strict samurai code to become the shadowy 'Ghost' to liberate his homeland.",
    quote: "HONOR DIED ON THE BEACH.",
    rank: "Rank #1 Samurai Sandbox",
    membersCount: "1.6M Players",
    trailerUrl: "https://www.youtube.com/embed/bZX_u_f0Nhs",
    tags: ["Jin Sakai", "Katana", "Kurosawa", "Tsushima", "Wind"],
    totalUnits: 50,
    unitType: "hours"
  },
  {
    id: "bloodborne",
    title: "Bloodborne",
    originalTitle: "Bloodborne",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://image.tmdb.org/t/p/w780/c8Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/nQ4iV63Kq2GqZ3kM8p0V2uF6m1N.jpg",
    rating: 9.5,
    ratingCount: "1.8M",
    year: 2015,
    ongoing: false,
    runtimeOrChapters: "45 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Soulslike", "Gothic Horror", "Lovecraftian", "Action RPG"],
    platformOrStudio: "FromSoftware / Hidetaka Miyazaki",
    synopsis: "A lone Hunter travels to the cursed Victorian city of Yharnam seeking the Paleblood, navigating beast-infested cobblestone alleys and eldritch Great Ones.",
    quote: "A HUNTER MUST HUNT.",
    rank: "Rank #1 Gothic Masterpiece",
    membersCount: "1.8M Players",
    trailerUrl: "https://www.youtube.com/embed/2Crk_GpxGQE",
    tags: ["Yharnam", "Trick Weapon", "Insight", "FromSoftware", "Miyazaki"],
    totalUnits: 45,
    unitType: "hours"
  },
  {
    id: "dark-souls-3",
    title: "Dark Souls III",
    originalTitle: "Dark Souls III",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/374320/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/w2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.3,
    ratingCount: "2.1M",
    year: 2016,
    ongoing: false,
    runtimeOrChapters: "60 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Soulslike", "Dark Fantasy", "Action RPG"],
    platformOrStudio: "FromSoftware / Bandai Namco",
    synopsis: "As the First Flame fades and the Lords of Cinder abandon their thrones, the Ashen One rises from the grave to rekindle the dying embers of the world.",
    quote: "MAYST THOU THY PEACE DISCOVER.",
    rank: "Rank #1 Soulslike Trilogy Climax",
    membersCount: "2.1M Players",
    trailerUrl: "https://www.youtube.com/embed/_zDZYrIUgKE",
    tags: ["Ashen One", "Lothric", "Soul of Cinder", "FromSoftware", "Bosses"],
    totalUnits: 60,
    unitType: "hours"
  },
  {
    id: "sekiro-shadows-die-twice",
    title: "Sekiro: Shadows Die Twice",
    originalTitle: "SEKIRO: SHADOWS DIE TWICE",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/yQxGv61nFqZ0nL0uF306b9qC0oT.jpg",
    rating: 9.4,
    ratingCount: "1.5M",
    year: 2019,
    ongoing: false,
    runtimeOrChapters: "40 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Action", "Stealth", "Soulslike", "Historical"],
    platformOrStudio: "FromSoftware / Activision",
    synopsis: "In Sengoku Japan, the 'One-Armed Wolf' shinobi protects his young Divine Heir lord Kuro from the desperate Ashina clan, deflecting blade strikes with rhythmic sword choreography.",
    quote: "HESITATION IS DEFEAT.",
    rank: "Game of the Year 2019",
    membersCount: "1.5M Players",
    trailerUrl: "https://www.youtube.com/embed/rXMX4YSTWF0",
    tags: ["Wolf", "Parry", "Deflection", "FromSoftware", "Isshin"],
    totalUnits: 40,
    unitType: "hours"
  },
  {
    id: "hollow-knight",
    title: "Hollow Knight",
    originalTitle: "Hollow Knight",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/p4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.5,
    ratingCount: "1.4M",
    year: 2017,
    ongoing: false,
    runtimeOrChapters: "50 Hours",
    ageRating: "E10+",
    genres: ["Metroidvania", "Soulslike", "Indie", "Dark Fantasy"],
    platformOrStudio: "Team Cherry",
    synopsis: "Descend into the forgotten subterranean bug kingdom of Hallownest to unravel ancient plagues, navigate haunting ruins, and face fierce insect warriors with your nail.",
    quote: "NO COST TOO GREAT. NO MIND TO THINK. NO WILL TO BREAK.",
    rank: "Rank #1 Indie Metroidvania",
    membersCount: "1.4M Players",
    trailerUrl: "https://www.youtube.com/embed/UAO2urG23S4",
    tags: ["The Knight", "Team Cherry", "Hallownest", "Hornet", "Silksong"],
    totalUnits: 50,
    unitType: "hours"
  },
  {
    id: "nier-automata",
    title: "NieR:Automata",
    originalTitle: "ニーア オートマタ",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/524220/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/gmECX1DvE9RiTeiKVPV7ndJTX8o.jpg",
    rating: 9.3,
    ratingCount: "1.3M",
    year: 2017,
    ongoing: false,
    runtimeOrChapters: "60 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Action RPG", "Hack and Slash", "Philosophical", "Sci-Fi"],
    platformOrStudio: "PlatinumGames / Square Enix / Yoko Taro",
    synopsis: "Androids 2B and 9S fight an unending proxy war on a deserted Earth against alien machine lifeforms, unraveling profound existential questions about humanity and soul.",
    quote: "EVERYTHING THAT LIVES IS DESIGNED TO END.",
    rank: "Rank #1 Philosophical Action Game",
    membersCount: "1.3M Players",
    trailerUrl: "https://www.youtube.com/embed/wJxNhJ8fjFk",
    tags: ["2B", "9S", "Yoko Taro", "Keiichi Okabe", "Ending E"],
    totalUnits: 60,
    unitType: "hours"
  },
  {
    id: "ff7-remake",
    title: "Final Fantasy VII Remake & Rebirth",
    originalTitle: "ファイナルファンタジーVII リメイク",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1462040/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/5n2P0F537K8Nl559Z9W3UvE3k2N.jpg",
    rating: 9.2,
    ratingCount: "1.7M",
    year: 2020,
    ongoing: true,
    runtimeOrChapters: "120+ Hours Total",
    ageRating: "T - Teen",
    genres: ["JRPG", "Action RPG", "Sci-Fi", "Fantasy"],
    platformOrStudio: "Square Enix",
    synopsis: "Ex-SOLDIER mercenary Cloud Strife joins eco-terrorist cell AVALANCHE in the mako-fueled metropolis of Midgar, defying fate itself against the enigmatic Sephiroth.",
    quote: "THE PLANET'S DYIN', CLOUD.",
    rank: "Rank #1 JRPG Reinvention",
    membersCount: "1.7M Players",
    trailerUrl: "https://www.youtube.com/embed/2k0Vv9C27X4",
    tags: ["Cloud", "Sephiroth", "Tifa", "Aerith", "Midgar"],
    totalUnits: 120,
    unitType: "hours"
  },
  {
    id: "persona-5-royal",
    title: "Persona 5 Royal",
    originalTitle: "ペルソナ5 ザ・ロイヤル",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1687950/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/tC3P1K9n7q8E2m5N4X6p8V1x9yP.jpg",
    rating: 9.5,
    ratingCount: "1.6M",
    year: 2019,
    ongoing: false,
    runtimeOrChapters: "120 Hours",
    ageRating: "M - Mature 17+",
    genres: ["JRPG", "Turn-Based", "Social Sim", "Anime"],
    platformOrStudio: "ATLUS",
    synopsis: "Donning the mask of Joker, a falsely accused high school student forms the Phantom Thieves of Hearts to steal corrupt desires from the cognitive Palaces of Tokyo's wicked adults.",
    quote: "TAKE YOUR HEART.",
    rank: "Rank #1 Modern JRPG Social Sim",
    membersCount: "1.6M Players",
    trailerUrl: "https://www.youtube.com/embed/SKpSpvFQZyE",
    tags: ["Joker", "Phantom Thieves", "Atlus", "Acid Jazz", "Tokyo"],
    totalUnits: 120,
    unitType: "hours"
  },
  {
    id: "hades-game",
    title: "Hades",
    originalTitle: "Hades",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/r2Vq7M6Q9Y2K6N8V1X9Z3p4b8U5.jpg",
    rating: 9.4,
    ratingCount: "1.3M",
    year: 2020,
    ongoing: false,
    runtimeOrChapters: "60 Hours",
    ageRating: "T - Teen",
    genres: ["Roguelike", "Action", "Mythology", "Indie"],
    platformOrStudio: "Supergiant Games",
    synopsis: "Zagreus, the rebellious Prince of the Underworld, defies his father Hades to battle up through Tartarus and Elysium to reach the mortal surface with boons from Olympus.",
    quote: "THERE IS NO ESCAPE.",
    rank: "Rank #1 Narrative Roguelike",
    membersCount: "1.3M Players",
    trailerUrl: "https://www.youtube.com/embed/mD8x5xLHRho",
    tags: ["Zagreus", "Supergiant", "Greek Mythology", "Olympus", "Roguelike"],
    totalUnits: 60,
    unitType: "hours"
  },
  {
    id: "resident-evil-4-remake",
    title: "Resident Evil 4 Remake",
    originalTitle: "バイオハザード RE:4",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/uCu4jN6r2F5pT5L7cQ7z0m0z0bE.jpg",
    rating: 9.4,
    ratingCount: "1.1M",
    year: 2023,
    ongoing: false,
    runtimeOrChapters: "25 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Survival Horror", "Action", "Zombies", "Third-Person"],
    platformOrStudio: "Capcom",
    synopsis: "Special agent Leon S. Kennedy is dispatched to a secluded European village to rescue the President's kidnapped daughter Ashley from the mind-controlling Los Illuminados cult.",
    quote: "WHERE'S EVERYONE GOING? BINGO?",
    rank: "Rank #1 Action Horror Remake",
    membersCount: "1.1M Players",
    trailerUrl: "https://www.youtube.com/embed/j5Xv2LXuW34",
    tags: ["Leon Kennedy", "Ashley", "Las Plagas", "Capcom", "Horror"],
    totalUnits: 25,
    unitType: "hours"
  },
  {
    id: "monster-hunter-world",
    title: "Monster Hunter: World",
    originalTitle: "モンスターハンター：ワールド",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/582010/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/vFlq03Xl3gJ5vB8k9M1P4E2m3X8.jpg",
    rating: 9.0,
    ratingCount: "1.8M",
    year: 2018,
    ongoing: false,
    runtimeOrChapters: "200+ Hours",
    ageRating: "T - Teen",
    genres: ["Action RPG", "Co-op", "Hunting", "Fantasy"],
    platformOrStudio: "Capcom",
    synopsis: "As part of the Fifth Fleet expedition to the untamed New World, hunters track formidable Elder Dragons across dynamic, living ecosystems to unravel the Elder Crossing.",
    quote: "MAY THE SAPPHIRE STAR LIGHT YOUR WAY.",
    rank: "Capcom's Best Selling Game of All Time",
    membersCount: "1.8M Players",
    trailerUrl: "https://www.youtube.com/embed/Ro6r15wZP2o",
    tags: ["New World", "Capcom", "Wyvern", "Co-op", "Elder Dragon"],
    totalUnits: 200,
    unitType: "hours"
  },
  {
    id: "black-myth-wukong",
    title: "Black Myth: Wukong",
    originalTitle: "黑神话：悟空",
    category: "gaming",
    mediaType: "game",
    coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/header.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/7eHn2P5Z0m2P1V6E4L2U9m8N7x1.jpg",
    rating: 9.2,
    ratingCount: "2.5M",
    year: 2024,
    ongoing: false,
    runtimeOrChapters: "45 Hours",
    ageRating: "M - Mature 17+",
    genres: ["Action RPG", "Mythology", "Soulslike", "Chinese Folklore"],
    platformOrStudio: "Game Science",
    synopsis: "Step into the fur of the Destined One to set out on a perilous expedition through ancient Chinese landscapes to recover the lost relics of the legendary Sun Wukong.",
    quote: "NO GOD CAN TAME THE MONKEY KING.",
    rank: "Fastest Selling Steam Release of 2024",
    membersCount: "2.5M Players",
    trailerUrl: "https://www.youtube.com/embed/pnSsgRF44cw",
    tags: ["Sun Wukong", "Journey to the West", "Staff", "Game Science", "Mythology"],
    totalUnits: 45,
    unitType: "hours"
  }
];
