module.exports = [
  {
    id: "vagabond",
    title: "Vagabond",
    originalTitle: "バガボンド",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/259070.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/p4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.3,
    ratingCount: "420K",
    year: 1998,
    ongoing: false,
    runtimeOrChapters: "327 Chapters (37 Vols)",
    ageRating: "Mature",
    genres: ["Action", "Historical", "Philosophical", "Seinen"],
    platformOrStudio: "Morning / Takehiko Inoue",
    synopsis: "Shinmen Takezo escapes the bloody aftermath of the Battle of Sekigahara and transforms into Miyamoto Musashi, embarking on a meditative quest to become 'Invincible under the Sun'.",
    quote: "PREOCCUPIED WITH A SINGLE LEAF, YOU WON'T SEE THE TREE.",
    rank: "Rank #2 All-Time Manga",
    membersCount: "420K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    featured: true,
    trending: true,
    tags: ["Musashi", "Inoue", "Bushido", "Brush Art", "Philosophy"],
    totalUnits: 327,
    unitType: "chapters",
    topArcs: [
      { title: "Yoshioka Clan Arc", range: "Ch. 200 - 240", description: "Musashi takes on 70 men alone in Kyoto.", status: "Masterpiece" },
      { title: "Farming Arc", range: "Ch. 300 - 327", description: "Musashi learns the rhythm of soil, rain, and life.", status: "Sublime" }
    ]
  },
  {
    id: "vinland-saga-manga",
    title: "Vinland Saga (Manga)",
    originalTitle: "ヴィンランド・サガ",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/188040.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/q2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.0,
    ratingCount: "350K",
    year: 2005,
    ongoing: true,
    runtimeOrChapters: "215+ Chapters",
    ageRating: "Mature",
    genres: ["Historical", "Action", "Drama", "Seinen"],
    platformOrStudio: "Afternoon / Makoto Yukimura",
    synopsis: "Thorfinn pursues vengeance against his father's killer Askeladd across 11th-century Viking Europe before learning true pacifism and sailing for the fertile shores of Vinland.",
    quote: "YOU HAVE NO ENEMIES. NO ONE IN THIS WORLD HAS ANY ENEMIES.",
    rank: "Rank #5 Seinen Manga",
    membersCount: "350K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Thorfinn", "Vikings", "Pacifism", "Askeladd", "Historical"],
    totalUnits: 215,
    unitType: "chapters"
  },
  {
    id: "20th-century-boys",
    title: "20th Century Boys",
    originalTitle: "20世紀少年",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/5/260006.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/w2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.9,
    ratingCount: "280K",
    year: 1999,
    ongoing: false,
    runtimeOrChapters: "249 Chapters (22 Vols)",
    ageRating: "Mature",
    genres: ["Mystery", "Sci-Fi", "Psychological", "Seinen"],
    platformOrStudio: "Big Comic Spirits / Naoki Urasawa",
    synopsis: "Kenji Endo and his childhood friends discover that an apocalyptic cult led by an enigmatic figure known as 'Friend' is executing the exact doomsday scenarios they wrote in a playground notebook.",
    quote: "EVEN IF WE ARE WEAK, WE CAN STILL FIGHT BACK.",
    rank: "Rank #1 Mystery Manga",
    membersCount: "280K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Naoki Urasawa", "Friend", "Conspiracy", "Rock and Roll", "Tokyo"],
    totalUnits: 249,
    unitType: "chapters"
  },
  {
    id: "oyasumi-punpun",
    title: "Goodnight Punpun",
    originalTitle: "おやすみプンプン (Oyasumi Punpun)",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/266834.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/r2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.0,
    ratingCount: "480K",
    year: 2007,
    ongoing: false,
    runtimeOrChapters: "147 Chapters (13 Vols)",
    ageRating: "Mature",
    genres: ["Drama", "Psychological", "Slice of Life", "Seinen"],
    platformOrStudio: "Big Comic Spirits / Inio Asano",
    synopsis: "Follows the devastating coming-of-age journey of Punpun Onodera, depicted as a simple bird silhouette against photorealistic backgrounds, dealing with dysfunctional family trauma and destructive love.",
    quote: "DEAR GOD, DEAR GOD, TINKLE TINKLE HOY.",
    rank: "Rank #1 Psychological Seinen",
    membersCount: "480K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Inio Asano", "Punpun", "Aiko", "Existential", "Melancholy"],
    totalUnits: 147,
    unitType: "chapters"
  },
  {
    id: "kingdom-manga",
    title: "Kingdom",
    originalTitle: "キングダム",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/171872.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/t2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.0,
    ratingCount: "210K",
    year: 2006,
    ongoing: true,
    runtimeOrChapters: "800+ Chapters",
    ageRating: "Mature",
    genres: ["Action", "Historical", "Military", "Seinen"],
    platformOrStudio: "Weekly Young Jump / Yasuhisa Hara",
    synopsis: "During China's Warring States period, war orphan Xin and King Ei Sei forge an alliance to conquer the rival six states and unite all of China under one throne.",
    quote: "I WILL BECOME THE GREATEST GENERAL UNDER THE HEAVENS!",
    rank: "Rank #1 War Epic Manga",
    membersCount: "210K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Shin", "Qin Dynasty", "Warring States", "Tactics", "Generals"],
    totalUnits: 800,
    unitType: "chapters"
  },
  {
    id: "jojo-steel-ball-run",
    title: "JoJo's Bizarre Adventure: Steel Ball Run",
    originalTitle: "ジョジョの奇妙な冒険 Part7 スティール・ボール・ラン",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/179882.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/u2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.3,
    ratingCount: "340K",
    year: 2004,
    ongoing: false,
    runtimeOrChapters: "95 Chapters (24 Vols)",
    ageRating: "Mature",
    genres: ["Action", "Adventure", "Supernatural", "Seinen"],
    platformOrStudio: "Ultra Jump / Hirohiko Araki",
    synopsis: "In 1890 America, paraplegic former jockey Johnny Joestar joins the Steel Ball Run cross-country horse race alongside Gyro Zeppeli, uncovering a sinister conspiracy involving the holy corpse parts.",
    quote: "THANK YOU, GYRO. THAT'S REALLY ALL I CAN SAY.",
    rank: "Rank #2 Highest Rated Manga",
    membersCount: "340K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Johnny Joestar", "Gyro Zeppeli", "Spin", "Stands", "Araki"],
    totalUnits: 95,
    unitType: "chapters"
  },
  {
    id: "slam-dunk-manga",
    title: "Slam Dunk",
    originalTitle: "スラムダンク",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/258749.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/v2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 9.0,
    ratingCount: "290K",
    year: 1990,
    ongoing: false,
    runtimeOrChapters: "276 Chapters (31 Vols)",
    ageRating: "Teen",
    genres: ["Sports", "Comedy", "School", "Shonen"],
    platformOrStudio: "Weekly Shonen Jump / Takehiko Inoue",
    synopsis: "Delinquent Hanamichi Sakuragi joins the Shohoku High basketball team to impress a girl, unexpectedly discovering a fierce athletic passion that leads the underdog squad toward the national championship.",
    quote: "HE WHO CONTROLS THE REBOUND CONTROLS THE GAME!",
    rank: "Rank #1 Sports Manga Legend",
    membersCount: "290K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Sakuragi", "Shohoku", "Takehiko Inoue", "Basketball", "Rebound"],
    totalUnits: 276,
    unitType: "chapters"
  },
  {
    id: "chainsaw-man-manga",
    title: "Chainsaw Man (Manga)",
    originalTitle: "チェンソーマン",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/216464.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/eU0Tg9n7pD3F5qFzZ3jU7a2V7uT.jpg",
    rating: 8.7,
    ratingCount: "680K",
    year: 2018,
    ongoing: true,
    runtimeOrChapters: "180+ Chapters",
    ageRating: "Mature",
    genres: ["Action", "Comedy", "Horror", "Supernatural"],
    platformOrStudio: "Shonen Jump+ / Tatsuki Fujimoto",
    synopsis: "Denji merges with his chainsaw devil pet Pochita to become Chainsaw Man, balancing bizarre teenage desires with cosmic devil battles and existential heartbreak.",
    quote: "IF I DIE, I DON'T CARE AS LONG AS I TOUCHED SOME BOOBS FIRST.",
    rank: "Rank #1 Modern Avant-Garde Shonen",
    membersCount: "680K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Fujimoto", "Denji", "Makima", "Asa Mitaka", "Gun Devil"],
    totalUnits: 180,
    unitType: "chapters"
  },
  {
    id: "jujutsu-kaisen-manga",
    title: "Jujutsu Kaisen (Manga)",
    originalTitle: "呪術廻戦",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/210341.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/gmECX1DvE9RiTeiKVPV7ndJTX8o.jpg",
    rating: 8.5,
    ratingCount: "590K",
    year: 2018,
    ongoing: false,
    runtimeOrChapters: "271 Chapters (Complete)",
    ageRating: "Mature",
    genres: ["Action", "Dark Fantasy", "Supernatural", "Shonen"],
    platformOrStudio: "Weekly Shonen Jump / Gege Akutami",
    synopsis: "The complete saga of Yuji Itadori, Satoru Gojo, and the sorcerers of Jujutsu High as they clash in Shibuya and the Shinjuku Showdown against the King of Curses Sukuna.",
    quote: "STAND PROUD, YOU ARE STRONG.",
    rank: "Rank #1 Manga Finale of 2024",
    membersCount: "590K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Gojo", "Sukuna", "Domain Expansion", "Gege Akutami", "Shinjuku"],
    totalUnits: 271,
    unitType: "chapters"
  },
  {
    id: "tokyo-ghoul-manga",
    title: "Tokyo Ghoul & :re",
    originalTitle: "東京喰種トーキョーグール",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/85371.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/s2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.5,
    ratingCount: "440K",
    year: 2011,
    ongoing: false,
    runtimeOrChapters: "322 Chapters Total",
    ageRating: "Mature",
    genres: ["Action", "Dark Fantasy", "Horror", "Psychological"],
    platformOrStudio: "Weekly Young Jump / Sui Ishida",
    synopsis: "Sui Ishida's complete, unedited masterpiece following Ken Kaneki and the Quinx squad through the moral quagmire of ghouls and human investigators in Tokyo.",
    quote: "THIS WORLD IS WRONG.",
    rank: "Rank #1 Psychological Seinen Masterwork",
    membersCount: "440K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Sui Ishida", "Kaneki", "Haise", "Arima", "Anteiku"],
    totalUnits: 322,
    unitType: "chapters"
  },
  {
    id: "gantz",
    title: "Gantz",
    originalTitle: "GANTZ",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/258751.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/x2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.1,
    ratingCount: "250K",
    year: 2000,
    ongoing: false,
    runtimeOrChapters: "383 Chapters (37 Vols)",
    ageRating: "Mature",
    genres: ["Action", "Sci-Fi", "Horror", "Psychological"],
    platformOrStudio: "Weekly Young Jump / Hiroya Oku",
    synopsis: "After being hit by a subway train, Kei Kurono awakens in an unfurnished Tokyo apartment dominated by a black sphere called Gantz that forces resurrected people to hunt grotesque aliens.",
    quote: "YOUR LIVES HAVE ENDED. HOW YOU USE YOUR NEW LIVES IS UP TO ME.",
    rank: "Rank #1 Sci-Fi Death Game",
    membersCount: "250K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Gantz", "Aliens", "Hiroya Oku", "Suit", "Osaka Arc"],
    totalUnits: 383,
    unitType: "chapters"
  },
  {
    id: "claymore-manga",
    title: "Claymore",
    originalTitle: "CLAYMORE",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/258752.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/y2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.3,
    ratingCount: "190K",
    year: 2001,
    ongoing: false,
    runtimeOrChapters: "155 Chapters (27 Vols)",
    ageRating: "Mature",
    genres: ["Action", "Adventure", "Dark Fantasy"],
    platformOrStudio: "Jump Square / Norihiro Yagi",
    synopsis: "In a medieval realm infested with flesh-eating Yoma, silver-eyed half-human warrior Clare wields a massive greatsword on a quest to avenge her mentor Teresa of the Faint Smile.",
    quote: "LIVE ON, CLARE.",
    rank: "Rank #2 Dark Fantasy Swords",
    membersCount: "190K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Silver Eyes", "Teresa", "Clare", "Yoma", "Awakened Being"],
    totalUnits: 155,
    unitType: "chapters"
  },
  {
    id: "uzumaki-junji-ito",
    title: "Uzumaki: Spiral into Horror",
    originalTitle: "うずまき",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/258753.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/z2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.2,
    ratingCount: "310K",
    year: 1998,
    ongoing: false,
    runtimeOrChapters: "20 Chapters (3 Vols)",
    ageRating: "Mature",
    genres: ["Horror", "Dementia", "Psychological", "Supernatural"],
    platformOrStudio: "Big Comic Spirits / Junji Ito",
    synopsis: "Kirie Goshima lives in the small, fogbound coastal town of Kurouzu-cho, which becomes cursed by an escalating, grotesque obsession with the spiral shape.",
    quote: "THIS TOWN IS CONTAMINATED WITH SPIRALS.",
    rank: "Rank #1 Horror Manga of All Time",
    membersCount: "310K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Junji Ito", "Body Horror", "Spiral", "Curse", "Masterpiece"],
    totalUnits: 20,
    unitType: "chapters"
  },
  {
    id: "homunculus-manga",
    title: "Homunculus",
    originalTitle: "ホムンクルス",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/258754.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/p2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.3,
    ratingCount: "180K",
    year: 2003,
    ongoing: false,
    runtimeOrChapters: "166 Chapters (15 Vols)",
    ageRating: "Mature",
    genres: ["Dementia", "Drama", "Horror", "Psychological"],
    platformOrStudio: "Big Comic Spirits / Hideo Yamamoto",
    synopsis: "A homeless former corporate banker agrees to undergo trepanation—a surgical drill through the skull—which awakens his ability to perceive human beings as warped, psychological homunculi.",
    quote: "WHAT DOES YOUR MONSTER LOOK LIKE?",
    rank: "Rank #1 Mind Distortion",
    membersCount: "180K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Trepanation", "Psychology", "Sixth Sense", "Hideo Yamamoto"],
    totalUnits: 166,
    unitType: "chapters"
  },
  {
    id: "fire-punch",
    title: "Fire Punch",
    originalTitle: "ファイアパンチ",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/258755.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/c8Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.0,
    ratingCount: "220K",
    year: 2016,
    ongoing: false,
    runtimeOrChapters: "83 Chapters (8 Vols)",
    ageRating: "Mature",
    genres: ["Action", "Mystery", "Supernatural", "Post-Apocalyptic"],
    platformOrStudio: "Shonen Jump+ / Tatsuki Fujimoto",
    synopsis: "In a frozen post-apocalyptic world, Agni is cursed with continuous high-speed regenerative powers while engulfed in never-extinguishing flames, marching across the ice for revenge.",
    quote: "LIVE, AGNI. LIVE.",
    rank: "Rank #1 Unhinged Seinen",
    membersCount: "220K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Tatsuki Fujimoto", "Agni", "Flames", "Cinema", "Dark Fantasy"],
    totalUnits: 83,
    unitType: "chapters"
  },
  {
    id: "houseki-no-kuni-manga",
    title: "Land of the Lustrous",
    originalTitle: "宝石の国 (Houseki no Kuni)",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/115443.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/tC3P1K9n7q8E2m5N4X6p8V1x9yP.jpg",
    rating: 8.9,
    ratingCount: "160K",
    year: 2012,
    ongoing: false,
    runtimeOrChapters: "108 Chapters (Complete)",
    ageRating: "Teen",
    genres: ["Action", "Drama", "Fantasy", "Philosophical"],
    platformOrStudio: "Afternoon / Haruko Ichikawa",
    synopsis: "In a distant future populated by immortal gem humanoid beings, fragile Phosphophyllite seeks a role among their siblings while defending against mysterious Moon invaders.",
    quote: "HAVE TEN THOUSAND YEARS OF EMPTINESS.",
    rank: "Rank #3 Philosophical Manga",
    membersCount: "160K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Phos", "Gems", "Buddhism", "Elegance", "Tragedy"],
    totalUnits: 108,
    unitType: "chapters"
  },
  {
    id: "sakamoto-days-manga",
    title: "Sakamoto Days",
    originalTitle: "SAKAMOTO DAYS",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/240751.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/r2Vq7M6Q9Y2K6N8V1X9Z3p4b8U5.jpg",
    rating: 8.2,
    ratingCount: "260K",
    year: 2020,
    ongoing: true,
    runtimeOrChapters: "180+ Chapters",
    ageRating: "Teen",
    genres: ["Action", "Comedy", "Shonen"],
    platformOrStudio: "Weekly Shonen Jump / Yuto Suzuki",
    synopsis: "Taro Sakamoto was once the world's most feared legendary assassin until he fell in love, retired, gained weight, and opened a neighborhood convenience store.",
    quote: "RULE NUMBER ONE: NO KILLING IN FRONT OF MY FAMILY.",
    rank: "Rank #1 Kinetic Action Shonen",
    membersCount: "260K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Assassins", "Action Choreography", "Sakamoto", "Store", "Shonen"],
    totalUnits: 180,
    unitType: "chapters"
  },
  {
    id: "dandadan-manga",
    title: "Dandadan",
    originalTitle: "ダンダダン",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/248740.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/m9kP4V1k3N0Q9p4m7U8E2v1x9yP.jpg",
    rating: 8.4,
    ratingCount: "320K",
    year: 2021,
    ongoing: true,
    runtimeOrChapters: "160+ Chapters",
    ageRating: "Teen",
    genres: ["Action", "Comedy", "Sci-Fi", "Supernatural"],
    platformOrStudio: "Shonen Jump+ / Yukinobu Tatsu",
    synopsis: "A ghost-believing girl and an alien-obsessed nerd investigate the supernatural to disprove each other, accidentally triggering an unhinged war involving Turbo Granny and Serpo aliens.",
    quote: "LET'S SEARCH FOR THE GOLDEN BALLS!",
    rank: "Rank #1 Sci-Fi Supernatural Comedy",
    membersCount: "320K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Aliens", "Yokai", "Turbo Granny", "Okarun", "Momo Ayase"],
    totalUnits: 160,
    unitType: "chapters"
  },
  {
    id: "kagurabachi-manga",
    title: "Kagurabachi",
    originalTitle: "カグラバチ",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/298450.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/7eHn2P5Z0m2P1V6E4L2U9m8N7x1.jpg",
    rating: 8.1,
    ratingCount: "190K",
    year: 2023,
    ongoing: true,
    runtimeOrChapters: "50+ Chapters",
    ageRating: "Teen",
    genres: ["Action", "Supernatural", "Shonen"],
    platformOrStudio: "Weekly Shonen Jump / Takeru Hokazono",
    synopsis: "Chihiro Rokuhira wields the enchanted katana forged by his late swordsmith father, hunting down the sorcerers who stole the six mystic blades to avenge his lineage.",
    quote: "ENOUGH TIME HAS PASSED.",
    rank: "Rank #1 Viral New-Gen Manga",
    membersCount: "190K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Enchanted Katana", "Chihiro", "Goldfish", "Sorcery", "Revenge"],
    totalUnits: 50,
    unitType: "chapters"
  },
  {
    id: "kokou-no-hito",
    title: "The Climber",
    originalTitle: "孤高の人 (Kokou no Hito)",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/121123.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/vFlq03Xl3gJ5vB8k9M1P4E2m3X8.jpg",
    rating: 8.8,
    ratingCount: "150K",
    year: 2007,
    ongoing: false,
    runtimeOrChapters: "170 Chapters (17 Vols)",
    ageRating: "Mature",
    genres: ["Drama", "Sports", "Psychological", "Seinen"],
    platformOrStudio: "Weekly Young Jump / Shinichi Sakamoto",
    synopsis: "Solitary climber Mori Buntaro finds meaning in solo alpine scaling, battling icy isolation, death-defying cliffs, and the crushing social demands of civilization.",
    quote: "UPON THE SUMMIT, THERE IS ONLY SILENCE AND TRUTH.",
    rank: "Rank #1 Extreme Sports Drama",
    membersCount: "150K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Mountaineering", "Shinichi Sakamoto", "Solo", "Snow", "Artistry"],
    totalUnits: 170,
    unitType: "chapters"
  },
  {
    id: "innocent-sakamoto",
    title: "Innocent & Innocent Rouge",
    originalTitle: "イノサン",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/159843.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/uCu4jN6r2F5pT5L7cQ7z0m0z0bE.jpg",
    rating: 8.4,
    ratingCount: "90K",
    year: 2013,
    ongoing: false,
    runtimeOrChapters: "180 Chapters Total",
    ageRating: "Mature",
    genres: ["Historical", "Drama", "Psychological", "Seinen"],
    platformOrStudio: "Weekly Young Jump / Shinichi Sakamoto",
    synopsis: "The breathtaking chronicle of Charles-Henri Sanson, the Royal Executioner of France who severed King Louis XVI's head while dreaming of an enlightened society free of capital punishment.",
    quote: "THE BLADE CLEANSES WHAT SOCIETY CORRUPTS.",
    rank: "Rank #1 French Revolution Art",
    membersCount: "90K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Guillotine", "Versailles", "Executioner", "Sakamoto", "Historical"],
    totalUnits: 180,
    unitType: "chapters"
  },
  {
    id: "billy-bat",
    title: "Billy Bat",
    originalTitle: "BILLY BAT",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/258756.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/nQ4iV63Kq2GqZ3kM8p0V2uF6m1N.jpg",
    rating: 8.3,
    ratingCount: "95K",
    year: 2008,
    ongoing: false,
    runtimeOrChapters: "165 Chapters (20 Vols)",
    ageRating: "Mature",
    genres: ["Mystery", "Historical", "Supernatural", "Seinen"],
    platformOrStudio: "Morning / Naoki Urasawa",
    synopsis: "Japanese-American comic artist Kevin Yamagata discovers his cartoon character Billy Bat has appeared at crucial turning points across human history from ancient scrolls to the Moon landing.",
    quote: "WHO DREW THE BAT FIRST?",
    rank: "Rank #3 Urasawa Masterpiece",
    membersCount: "95K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Urasawa", "Conspiracy", "JFK", "Moon Landing", "History"],
    totalUnits: 165,
    unitType: "chapters"
  },
  {
    id: "pluto-manga",
    title: "Pluto (Manga)",
    originalTitle: "PLUTO",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/258757.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/5n2P0F537K8Nl559Z9W3UvE3k2N.jpg",
    rating: 8.6,
    ratingCount: "130K",
    year: 2003,
    ongoing: false,
    runtimeOrChapters: "65 Chapters (8 Vols)",
    ageRating: "Mature",
    genres: ["Action", "Mystery", "Mecha", "Sci-Fi", "Seinen"],
    platformOrStudio: "Big Comic Original / Naoki Urasawa",
    synopsis: "Naoki Urasawa reimagines Osamu Tezuka's Astro Boy 'Greatest Robot on Earth' story as a gritty detective murder mystery following Europol inspector Gesicht.",
    quote: "NOTHING COMES FROM HATRED, EXCEPT MORE HATRED.",
    rank: "Rank #1 Sci-Fi Noir Manga",
    membersCount: "130K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Gesicht", "Atom", "Astro Boy", "AI", "Urasawa"],
    totalUnits: 65,
    unitType: "chapters"
  },
  {
    id: "lone-wolf-and-cub",
    title: "Lone Wolf and Cub",
    originalTitle: "子連れ狼 (Kozure Ookami)",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/258758.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/iA5L1P0gG6m35eF1VqBqO01Z1z0.jpg",
    rating: 8.7,
    ratingCount: "75K",
    year: 1970,
    ongoing: false,
    runtimeOrChapters: "142 Chapters (28 Vols)",
    ageRating: "Mature",
    genres: ["Action", "Historical", "Samurai", "Seinen"],
    platformOrStudio: "Manga Action / Kazuo Koike & Goseki Kojima",
    synopsis: "Disgraced Shogunate executioner Ogami Itto travels feudal Japan with his infant son Daigoro in a baby cart packed with weapons, offering his sword for hire.",
    quote: "CHOOSE THE SWORD OR CHOOSE THE BALL.",
    rank: "Rank #1 Historical Samurai Classic",
    membersCount: "75K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Ogami Itto", "Daigoro", "Samurai", "Classic", "Edo"],
    totalUnits: 142,
    unitType: "chapters"
  },
  {
    id: "dragon-ball-manga",
    title: "Dragon Ball & Dragon Ball Z",
    originalTitle: "DRAGON BALL",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/258759.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/2rmK7mnchq9fd8dnfZ52cqQx7MN.jpg",
    rating: 8.7,
    ratingCount: "510K",
    year: 1984,
    ongoing: false,
    runtimeOrChapters: "519 Chapters (42 Vols)",
    ageRating: "Teen",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Shonen"],
    platformOrStudio: "Weekly Shonen Jump / Akira Toriyama",
    synopsis: "Akira Toriyama's timeless masterpiece following Son Goku from a monkey-tailed martial artist into the universe's ultimate Super Saiyan defender.",
    quote: "KAMEHAMEHA!",
    rank: "Rank #1 Father of Modern Shonen",
    membersCount: "510K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Goku", "Akira Toriyama", "Super Saiyan", "Dragon Balls", "Kamehameha"],
    totalUnits: 519,
    unitType: "chapters"
  },
  {
    id: "nausicaa-manga",
    title: "Nausicaä of the Valley of the Wind (Manga)",
    originalTitle: "風の谷のナウシカ",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/258760.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/nTvM4mhqZlHIvUkI1gVnW6XP7GG.jpg",
    rating: 8.9,
    ratingCount: "85K",
    year: 1982,
    ongoing: false,
    runtimeOrChapters: "59 Chapters (7 Vols)",
    ageRating: "Teen",
    genres: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
    platformOrStudio: "Animage / Hayao Miyazaki",
    synopsis: "Hayao Miyazaki's 12-year magnum opus epic following Princess Nausicaä through the toxic Sea of Corruption, far more sprawling and complex than the animated film.",
    quote: "NO MATTER HOW DIFFICULT, WE MUST LIVE.",
    rank: "Rank #1 Miyazaki Literary Achievement",
    membersCount: "85K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Miyazaki", "Ohm", "Toxic Jungle", "Eco Epic", "Masterpiece"],
    totalUnits: 59,
    unitType: "chapters"
  },
  {
    id: "witch-hat-atelier",
    title: "Witch Hat Atelier",
    originalTitle: "とんがり帽子のアトリエ",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/194488.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/gmECX1DvE9RiTeiKVPV7ndJTX8o.jpg",
    rating: 8.6,
    ratingCount: "90K",
    year: 2016,
    ongoing: true,
    runtimeOrChapters: "80+ Chapters",
    ageRating: "Teen",
    genres: ["Fantasy", "Seinen"],
    platformOrStudio: "Morning Two / Kamome Shirahama",
    synopsis: "Coco, a humble village girl who has always dreamed of magic, learns that spells are drawn with specialized ink and joins an atelier of apprentice witches.",
    quote: "MAGIC IS THE ART OF GIVING SHAPE TO COMPASSION.",
    rank: "Rank #1 High Fantasy Illustration",
    membersCount: "90K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Magic Inks", "Kamome Shirahama", "Atelier", "Ghibli-esque", "Fantasy"],
    totalUnits: 80,
    unitType: "chapters"
  },
  {
    id: "frieren-manga",
    title: "Frieren: Beyond Journey's End (Manga)",
    originalTitle: "葬送のフリーレン",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/234716.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/yQxGv61nFqZ0nL0uF306b9qC0oT.jpg",
    rating: 8.9,
    ratingCount: "250K",
    year: 2020,
    ongoing: true,
    runtimeOrChapters: "135+ Chapters",
    ageRating: "Teen",
    genres: ["Adventure", "Drama", "Fantasy", "Shonen"],
    platformOrStudio: "Weekly Shonen Sunday / Kanehito Yamada & Tsukasa Abe",
    synopsis: "The elf mage Frieren reflects upon her decades-long adventure with the Hero party after her human companions pass away from old age, retracing their steps to understand human hearts.",
    quote: "AFTER ALL, ONLY A MERE PERCENT OF MY LIFE WAS SPENT WITH HIM.",
    rank: "Rank #1 Melancholy Fantasy",
    membersCount: "250K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Frieren", "Himmel", "Elf", "Passage of Time", "Magic"],
    totalUnits: 135,
    unitType: "chapters"
  },
  {
    id: "blue-lock-manga",
    title: "Blue Lock (Manga)",
    originalTitle: "ブルーロック",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/220267.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/notKMY2Fv84.jpg",
    rating: 8.3,
    ratingCount: "230K",
    year: 2018,
    ongoing: true,
    runtimeOrChapters: "270+ Chapters",
    ageRating: "Teen",
    genres: ["Sports", "Shonen"],
    platformOrStudio: "Weekly Shonen Magazine / Muneyuki Kaneshiro & Yusuke Nomura",
    synopsis: "Three hundred elite high school strikers are locked in a prison-like facility called Blue Lock where 299 will be eliminated to forge Japan's ultimate egoist World Cup striker.",
    quote: "UNLESS YOU HAVE THE EGO TO BE THE WORLD'S BEST, YOU WILL NEVER BE AN ACE.",
    rank: "Rank #1 Modern Sports Manga",
    membersCount: "230K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Isagi", "Ego", "Soccer", "Egoism", "Visual Intensity"],
    totalUnits: 270,
    unitType: "chapters"
  },
  {
    id: "real-takehiko-inoue",
    title: "REAL",
    originalTitle: "リアル",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/115599.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/p4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.8,
    ratingCount: "85K",
    year: 1999,
    ongoing: true,
    runtimeOrChapters: "95+ Chapters",
    ageRating: "Mature",
    genres: ["Drama", "Sports", "Seinen"],
    platformOrStudio: "Weekly Young Jump / Takehiko Inoue",
    synopsis: "Takehiko Inoue's moving exploration of wheelchair basketball, following three young men dealing with paralysis, guilt, athletic ambition, and societal marginalization.",
    quote: "THIS CHAIR IS NOT A PRISON. IT IS MY COURT.",
    rank: "Rank #1 Inspirational Seinen",
    membersCount: "85K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Wheelchair Basketball", "Inoue", "Redemption", "Athletes", "Realism"],
    totalUnits: 95,
    unitType: "chapters"
  },
  {
    id: "bleach-manga",
    title: "Bleach (Manga)",
    originalTitle: "BLEACH",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/180082.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/2wWh7028h7nFwS60N8qF38B8A0E.jpg",
    rating: 8.2,
    ratingCount: "480K",
    year: 2001,
    ongoing: false,
    runtimeOrChapters: "686 Chapters (74 Vols)",
    ageRating: "Teen",
    genres: ["Action", "Adventure", "Supernatural", "Shonen"],
    platformOrStudio: "Weekly Shonen Jump / Tite Kubo",
    synopsis: "Tite Kubo's masterclass in streetwear aesthetics, Japanese calligraphy, and Soul Reaper combat following Ichigo Kurosaki through the Soul Society and Hueco Mundo.",
    quote: "WE FEAR THAT WHICH WE CANNOT SEE.",
    rank: "Big Three Shonen Titan",
    membersCount: "480K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Ichigo", "Tite Kubo", "Bankai", "Zanpakuto", "Aizen"],
    totalUnits: 686,
    unitType: "chapters"
  },
  {
    id: "hunter-x-hunter-manga",
    title: "Hunter x Hunter (Manga)",
    originalTitle: "HUNTER×HUNTER",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/258761.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/q6i04M5K65C17b5B2A9pA1jF4g0.jpg",
    rating: 8.9,
    ratingCount: "380K",
    year: 1998,
    ongoing: true,
    runtimeOrChapters: "400+ Chapters",
    ageRating: "Mature",
    genres: ["Action", "Adventure", "Fantasy", "Shonen"],
    platformOrStudio: "Weekly Shonen Jump / Yoshihiro Togashi",
    synopsis: "Yoshihiro Togashi's hyper-strategic masterpiece, expanding far beyond the Chimera Ant arc into the complex geopolitical Succession War aboard the Black Whale heading for the Dark Continent.",
    quote: "NEN IS LIMITED ONLY BY INTELLECT AND RESOLVE.",
    rank: "Rank #1 Strategic Battle Manga",
    membersCount: "380K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Togashi", "Kurapika", "Dark Continent", "Succession War", "Nen"],
    totalUnits: 400,
    unitType: "chapters"
  },
  {
    id: "death-note-manga",
    title: "Death Note (Manga)",
    originalTitle: "DEATH NOTE",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/258762.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/iA5L1P0gG6m35eF1VqBqO01Z1z0.jpg",
    rating: 8.8,
    ratingCount: "420K",
    year: 2003,
    ongoing: false,
    runtimeOrChapters: "108 Chapters (12 Vols)",
    ageRating: "Teen",
    genres: ["Mystery", "Psychological", "Supernatural", "Shonen"],
    platformOrStudio: "Weekly Shonen Jump / Tsugumi Ohba & Takeshi Obata",
    synopsis: "The definitive original print battle between Light Yagami and the world's master detective L, renowned for Takeshi Obata's meticulous gothic linework.",
    quote: "I AM JUSTICE!",
    rank: "Rank #1 Detective Manga",
    membersCount: "420K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Light", "L", "Obata", "Shinigami", "Kira"],
    totalUnits: 108,
    unitType: "chapters"
  },
  {
    id: "fullmetal-alchemist-manga",
    title: "Fullmetal Alchemist (Manga)",
    originalTitle: "鋼の錬金術師",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/258763.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/2rmK7mnchq9fd8dnfZ52cqQx7MN.jpg",
    rating: 9.1,
    ratingCount: "370K",
    year: 2001,
    ongoing: false,
    runtimeOrChapters: "108 Chapters (27 Vols)",
    ageRating: "Teen",
    genres: ["Action", "Adventure", "Fantasy", "Drama", "Shonen"],
    platformOrStudio: "Monthly Shonen Gangan / Hiromu Arakawa",
    synopsis: "Hiromu Arakawa's immaculate narrative clockwork exploring human sacrifice, state militarism, alchemy, and brotherly devotion.",
    quote: "EQUIVALENT EXCHANGE.",
    rank: "Rank #1 Perfect Pacing Manga",
    membersCount: "370K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Arakawa", "Edward Elric", "Alphonse", "Alchemy", "Masterpiece"],
    totalUnits: 108,
    unitType: "chapters"
  },
  {
    id: "blade-of-the-immortal",
    title: "Blade of the Immortal",
    originalTitle: "無限の住人 (Mugen no Juunin)",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/258764.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/yQxGv61nFqZ0nL0uF306b9qC0oT.jpg",
    rating: 8.5,
    ratingCount: "110K",
    year: 1993,
    ongoing: false,
    runtimeOrChapters: "207 Chapters (30 Vols)",
    ageRating: "Mature",
    genres: ["Action", "Historical", "Supernatural", "Seinen"],
    platformOrStudio: "Afternoon / Hiroaki Samura",
    synopsis: "Cursed with sacred bloodworms that heal any mortal wound, master swordsman Manji agrees to slay 1,000 evil men to regain his mortality, acting as bodyguard to orphan Rin.",
    quote: "TO LIVE WITHOUT DYING IS THE CRUELEST HELL.",
    rank: "Rank #2 Edo Swordplay",
    membersCount: "110K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Manji", "Hiroaki Samura", "Bloodworms", "Samurai", "Swords"],
    totalUnits: 207,
    unitType: "chapters"
  },
  {
    id: "akira-manga",
    title: "Akira (Manga)",
    originalTitle: "AKIRA",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/258765.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/k4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.8,
    ratingCount: "160K",
    year: 1982,
    ongoing: false,
    runtimeOrChapters: "120 Chapters (6 Huge Vols)",
    ageRating: "Mature",
    genres: ["Action", "Sci-Fi", "Seinen"],
    platformOrStudio: "Young Magazine / Katsuhiro Otomo",
    synopsis: "Katsuhiro Otomo's staggering 2,000-page graphic monument detailing the complete collapse, military coup, and psychic resurrection of post-nuclear Neo-Tokyo.",
    quote: "I AM TETSUO.",
    rank: "Rank #1 Graphic Novel Masterpiece",
    membersCount: "160K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Neo Tokyo", "Otomo", "Psychic", "Cyberpunk", "Legend"],
    totalUnits: 120,
    unitType: "chapters"
  },
  {
    id: "choujin-x",
    title: "Choujin X",
    originalTitle: "超人X",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/3/245873.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/s2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
    rating: 8.0,
    ratingCount: "110K",
    year: 2021,
    ongoing: true,
    runtimeOrChapters: "60+ Chapters",
    ageRating: "Mature",
    genres: ["Action", "Psychological", "Supernatural", "Seinen"],
    platformOrStudio: "Tonari no Young Jump / Sui Ishida",
    synopsis: "High schooler Tokio Kurohara lives in the shadow of his accomplished friend Azuma until they inject themselves with a mysterious Choujin syringe to survive a rogue mutant assault.",
    quote: "BECOME A BEAST TO SURVIVE THE HUMAN WORLD.",
    rank: "Rank #1 Dark Metamorphosis",
    membersCount: "110K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Sui Ishida", "Tokio", "Choujin", "Vulture", "Supernatural"],
    totalUnits: 60,
    unitType: "chapters"
  },
  {
    id: "yokohama-kaidashi-kikou",
    title: "Yokohama Kaidashi Kikou",
    originalTitle: "ヨコハマ買い出し紀行",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/1/171871.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/qD211Hb5XwFxrszzBBe5EUYJerh.jpg",
    rating: 8.7,
    ratingCount: "70K",
    year: 1994,
    ongoing: false,
    runtimeOrChapters: "142 Chapters (14 Vols)",
    ageRating: "Teen",
    genres: ["Sci-Fi", "Slice of Life", "Seinen"],
    platformOrStudio: "Afternoon / Hitoshi Ashinano",
    synopsis: "In a gentle post-human world where sea levels have peacefully submerged coastal cities, an android named Alpha runs a quiet coffee shop in the Miura Peninsula countryside.",
    quote: "EVEN AS THE WORLD WINDS DOWN, COFFEE REMAINS DELICIOUS.",
    rank: "Rank #1 Iyashikei Post-Apocalypse",
    membersCount: "70K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Alpha", "Coffee", "Peaceful", "Submerged", "Atmospheric"],
    totalUnits: 142,
    unitType: "chapters"
  },
  {
    id: "haikyuu-manga",
    title: "Haikyuu!! (Manga)",
    originalTitle: "ハイキュー!!",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/258766.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/m9kP4V1k3N0Q9p4m7U8E2v1x9yP.jpg",
    rating: 8.9,
    ratingCount: "280K",
    year: 2012,
    ongoing: false,
    runtimeOrChapters: "402 Chapters (45 Vols)",
    ageRating: "Teen",
    genres: ["Sports", "School", "Shonen"],
    platformOrStudio: "Weekly Shonen Jump / Haruichi Furudate",
    synopsis: "The complete volleyball epic following Hinata and Kageyama all the way from their high school gym through the Spring National tournament and into professional global leagues.",
    quote: "TODAY YOU MIGHT BE THE DEFEATED. BUT WHAT WILL YOU BE TOMORROW?",
    rank: "Rank #1 Modern Sports Narrative",
    membersCount: "280K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Karasuno", "Volleyball", "Furudate", "Inarizaki", "Nekoma"],
    totalUnits: 402,
    unitType: "chapters"
  },
  {
    id: "attack-on-titan-manga",
    title: "Attack on Titan (Manga)",
    originalTitle: "進撃の巨人",
    category: "manga",
    mediaType: "manga",
    coverImage: "https://cdn.myanimelist.net/images/manga/2/37846.jpg",
    bannerImage: "https://image.tmdb.org/t/p/w1280/yQxGv61nFqZ0nL0uF306b9qC0oT.jpg",
    rating: 8.6,
    ratingCount: "620K",
    year: 2009,
    ongoing: false,
    runtimeOrChapters: "139 Chapters (34 Vols)",
    ageRating: "Mature",
    genres: ["Action", "Dark Fantasy", "Post-Apocalyptic", "Mystery"],
    platformOrStudio: "Bessatsu Shonen Magazine / Hajime Isayama",
    synopsis: "Hajime Isayama's groundbreaking dark fantasy manga that redefined modern manga global reach with shocking plot twists, political dread, and geopolitical devastation.",
    quote: "TO GAIN FREEDOM, I WILL TAKE THE FREEDOM OF THE WORLD.",
    rank: "Rank #1 Global Cultural Phenomenon",
    membersCount: "620K Members",
    trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
    tags: ["Isayama", "Eren", "Rumbling", "Paradis", "Marley"],
    totalUnits: 139,
    unitType: "chapters"
  }
];
