module.exports = {
  moreGaming: [
    {
      id: "helldivers-2",
      title: "Helldivers 2",
      originalTitle: "Helldivers 2",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/553850/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/yQxGv61nFqZ0nL0uF306b9qC0oT.jpg",
      rating: 9.1,
      ratingCount: "1.2M",
      year: 2024,
      ongoing: true,
      runtimeOrChapters: "100+ Hours",
      ageRating: "M - Mature 17+",
      genres: ["Co-op", "Shooter", "Sci-Fi", "Action"],
      platformOrStudio: "Arrowhead / PlayStation",
      synopsis: "Join the Helldivers and fight for Freedom across a hostile galaxy in a fast, frantic, and ferocious third-person co-op squad shooter.",
      quote: "FOR DEMOCRACY!",
      rank: "Top Co-op Shooter of 2024",
      membersCount: "1.2M Players",
      trailerUrl: "https://www.youtube.com/embed/l_nkgkG8r3g",
      tags: ["Super Earth", "Democracy", "Stratagem", "Automaton", "Terminid"],
      totalUnits: 100,
      unitType: "hours"
    },
    {
      id: "alan-wake-2",
      title: "Alan Wake 2",
      originalTitle: "Alan Wake 2",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://image.tmdb.org/t/p/w780/k4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/p4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
      rating: 9.3,
      ratingCount: "850K",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "25 Hours",
      ageRating: "M - Mature 17+",
      genres: ["Survival Horror", "Psychological", "Mystery"],
      platformOrStudio: "Remedy Entertainment / Epic Games",
      synopsis: "FBI agent Saga Anderson investigates ritualistic murders in Bright Falls while tortured writer Alan Wake writes a reality-bending manuscript to escape the Dark Place.",
      quote: "IT'S NOT A LOOP, IT'S A SPIRAL.",
      rank: "Rank #1 Mind-Bending Horror",
      membersCount: "850K Players",
      trailerUrl: "https://www.youtube.com/embed/qK1b2M3r8bA",
      tags: ["Alan Wake", "Saga", "Remedy", "Dark Place", "Live Action"],
      totalUnits: 25,
      unitType: "hours"
    },
    {
      id: "control-game",
      title: "Control",
      originalTitle: "Control",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/gmECX1DvE9RiTeiKVPV7ndJTX8o.jpg",
      rating: 8.8,
      ratingCount: "920K",
      year: 2019,
      ongoing: false,
      runtimeOrChapters: "20 Hours",
      ageRating: "M - Mature 17+",
      genres: ["Action", "Sci-Fi", "Supernatural", "Metroidvania"],
      platformOrStudio: "Remedy Entertainment / 505 Games",
      synopsis: "Jesse Faden enters the shifting brutalist headquarters of the Federal Bureau of Control, wielding the Service Weapon and telekinetic powers to purge the corrupting Hiss.",
      quote: "YOU ARE A WORM THROUGH TIME.",
      rank: "Rank #1 Brutalist Sci-Fi",
      membersCount: "920K Players",
      trailerUrl: "https://www.youtube.com/embed/PT5yMfC9LQM",
      tags: ["Oldest House", "Jesse Faden", "Telekinesis", "Remedy", "SCP"],
      totalUnits: 20,
      unitType: "hours"
    },
    {
      id: "disco-elysium",
      title: "Disco Elysium - The Final Cut",
      originalTitle: "Disco Elysium",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/632470/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/5n2P0F537K8Nl559Z9W3UvE3k2N.jpg",
      rating: 9.7,
      ratingCount: "890K",
      year: 2019,
      ongoing: false,
      runtimeOrChapters: "45 Hours",
      ageRating: "M - Mature 17+",
      genres: ["CRPG", "Detective", "Story-Rich", "Philosophical"],
      platformOrStudio: "ZA/UM",
      synopsis: "You're a detective with a unique skill system and a whole city to carve your path across in Revachol, interrogating unforgettable characters and unravelling an amnesiac murder mystery.",
      quote: "SOMETHING BEAUTIFUL IS GOING TO HAPPEN.",
      rank: "Rank #1 Written Game Script of All Time",
      membersCount: "890K Players",
      trailerUrl: "https://www.youtube.com/embed/5aU_rE1G_3E",
      tags: ["Revachol", "Kim Kitsuragi", "Thought Cabinet", "ZA/UM", "Literature"],
      totalUnits: 45,
      unitType: "hours"
    },
    {
      id: "armored-core-6",
      title: "Armored Core VI: Fires of Rubicon",
      originalTitle: "ARMORED CORE VI FIRES OF RUBICON",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1888110/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/tC3P1K9n7q8E2m5N4X6p8V1x9yP.jpg",
      rating: 9.1,
      ratingCount: "780K",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "35 Hours",
      ageRating: "T - Teen",
      genres: ["Action", "Mecha", "Sci-Fi", "Customization"],
      platformOrStudio: "FromSoftware / Bandai Namco",
      synopsis: "Augmented human C4-621 infiltrates the contaminated frontier planet Rubicon 3 as an independent mercenary, deploying high-speed customized mechas in omnidirectional combat.",
      quote: "I WON'T MISS.",
      rank: "Rank #1 Mecha Action Game",
      membersCount: "780K Players",
      trailerUrl: "https://www.youtube.com/embed/HmsZ_eWk98A",
      tags: ["Rubicon", "Raven", "FromSoftware", "Mecha", "Coral"],
      totalUnits: 35,
      unitType: "hours"
    },
    {
      id: "lies-of-p",
      title: "Lies of P",
      originalTitle: "Lies of P",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1627720/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/r2Vq7M6Q9Y2K6N8V1X9Z3p4b8U5.jpg",
      rating: 9.0,
      ratingCount: "680K",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "35 Hours",
      ageRating: "M - Mature 17+",
      genres: ["Soulslike", "Action RPG", "Dark Fantasy", "Steampunk"],
      platformOrStudio: "Round8 Studio / Neowiz",
      synopsis: "Guide puppet Pinocchio through the blood-soaked Belle Époque city of Krat, fighting deranged puppets and infected carcasses while choosing whether to lie or speak the truth to become human.",
      quote: "YOUR SPRINGS ARE REACTING.",
      rank: "Rank #1 Modern Soulslike Tribute",
      membersCount: "680K Players",
      trailerUrl: "https://www.youtube.com/embed/6iO2g_P2p4Y",
      tags: ["Pinocchio", "Krat", "Puppets", "Soulslike", "Parry"],
      totalUnits: 35,
      unitType: "hours"
    },
    {
      id: "grand-theft-auto-v",
      title: "Grand Theft Auto V",
      originalTitle: "Grand Theft Auto V",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/uCu4jN6r2F5pT5L7cQ7z0m0z0bE.jpg",
      rating: 9.6,
      ratingCount: "4.5M",
      year: 2013,
      ongoing: true,
      runtimeOrChapters: "80+ Hours",
      ageRating: "M - Mature 17+",
      genres: ["Open World", "Action", "Crime", "Multiplayer"],
      platformOrStudio: "Rockstar Games",
      synopsis: "When a young street hustler, a retired bank robber, and a terrifying psychopath find themselves entangled with some of the most frightening elements of the criminal underworld, they must pull off a series of dangerous heists.",
      quote: "WELCOME TO LOS SANTOS.",
      rank: "Best Selling Entertainment Product in History",
      membersCount: "4.5M Players",
      trailerUrl: "https://www.youtube.com/embed/QkkoHAzJnUs",
      tags: ["Los Santos", "Michael", "Trevor", "Franklin", "Rockstar"],
      totalUnits: 80,
      unitType: "hours"
    },
    {
      id: "marvel-spider-man-remastered",
      title: "Marvel's Spider-Man Remastered",
      originalTitle: "Marvel's Spider-Man",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/vFlq03Xl3gJ5vB8k9M1P4E2m3X8.jpg",
      rating: 9.3,
      ratingCount: "2.1M",
      year: 2018,
      ongoing: false,
      runtimeOrChapters: "30 Hours",
      ageRating: "T - Teen",
      genres: ["Action", "Open World", "Superhero"],
      platformOrStudio: "Insomniac Games / PlayStation",
      synopsis: "Experience an experienced Peter Parker swinging through a vibrant New York City, balancing his chaotic personal life and career with the fate of millions when Mister Negative threatens Manhattan.",
      quote: "BE GREATER.",
      rank: "Rank #1 Superhero Video Game",
      membersCount: "2.1M Players",
      trailerUrl: "https://www.youtube.com/embed/q4Go_Yx9_1E",
      tags: ["Spider-Man", "Peter Parker", "Web Swinging", "Insomniac", "New York"],
      totalUnits: 30,
      unitType: "hours"
    },
    {
      id: "marvel-spider-man-2",
      title: "Marvel's Spider-Man 2",
      originalTitle: "Marvel's Spider-Man 2",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://image.tmdb.org/t/p/w780/7eHn2P5Z0m2P1V6E4L2U9m8N7x1.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/nQ4iV63Kq2GqZ3kM8p0V2uF6m1N.jpg",
      rating: 9.2,
      ratingCount: "1.4M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "30 Hours",
      ageRating: "T - Teen",
      genres: ["Action", "Open World", "Superhero"],
      platformOrStudio: "Insomniac Games / PlayStation",
      synopsis: "Spider-Men Peter Parker and Miles Morales face the ultimate test of strength both inside and outside the mask as Kraven the Hunter arrives and the Symbiote bonds with Peter.",
      quote: "BE GREATER. TOGETHER.",
      rank: "Rank #1 Dual Protagonist Comic Game",
      membersCount: "1.4M Players",
      trailerUrl: "https://www.youtube.com/embed/9fVYKsEmuRo",
      tags: ["Venom", "Miles Morales", "Symbiote", "Kraven", "Insomniac"],
      totalUnits: 30,
      unitType: "hours"
    },
    {
      id: "mass-effect-legendary-edition",
      title: "Mass Effect Legendary Edition",
      originalTitle: "Mass Effect Legendary Edition",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1328670/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/w2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
      rating: 9.6,
      ratingCount: "1.7M",
      year: 2021,
      ongoing: false,
      runtimeOrChapters: "120 Hours",
      ageRating: "M - Mature 17+",
      genres: ["RPG", "Sci-Fi", "Third-Person Shooter", "Story-Rich"],
      platformOrStudio: "BioWare / Electronic Arts",
      synopsis: "Relive the epic space opera trilogy as Commander Shepard, uniting disparate galactic civilizations aboard the SSV Normandy to repel the ancient synthetic scourge known as the Reapers.",
      quote: "I'M COMMANDER SHEPARD, AND THIS IS MY FAVORITE STORE ON THE CITADEL.",
      rank: "Rank #1 Sci-Fi RPG Trilogy",
      membersCount: "1.7M Players",
      trailerUrl: "https://www.youtube.com/embed/n8i53TtQ6BQ",
      tags: ["Commander Shepard", "Normandy", "Reapers", "BioWare", "Citadel"],
      totalUnits: 120,
      unitType: "hours"
    },
    {
      id: "skyrim",
      title: "The Elder Scrolls V: Skyrim",
      originalTitle: "The Elder Scrolls V: Skyrim",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/489830/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/yQxGv61nFqZ0nL0uF306b9qC0oT.jpg",
      rating: 9.5,
      ratingCount: "3.5M",
      year: 2011,
      ongoing: false,
      runtimeOrChapters: "250+ Hours",
      ageRating: "M - Mature 17+",
      genres: ["Open World", "RPG", "Fantasy", "Action"],
      platformOrStudio: "Bethesda Game Studios",
      synopsis: "The dragons have returned to Tamriel. You are the Dragonborn, the prophesied hero born with the soul of a dragon, destined to stand against the World-Eater Alduin.",
      quote: "FUS RO DAH!",
      rank: "Game of the Decade Contender",
      membersCount: "3.5M Players",
      trailerUrl: "https://www.youtube.com/embed/JSRtYpNRoN0",
      tags: ["Dovahkiin", "Bethesda", "Open World", "Dragons", "Mods"],
      totalUnits: 250,
      unitType: "hours"
    },
    {
      id: "fallout-new-vegas-game",
      title: "Fallout: New Vegas",
      originalTitle: "Fallout: New Vegas",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/22380/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/p4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
      rating: 9.4,
      ratingCount: "1.9M",
      year: 2010,
      ongoing: false,
      runtimeOrChapters: "80 Hours",
      ageRating: "M - Mature 17+",
      genres: ["RPG", "Post-Apocalyptic", "Open World", "Choices Matter"],
      platformOrStudio: "Obsidian Entertainment / Bethesda",
      synopsis: "Shot in the head and left for dead in a shallow grave, a Mojave Express Courier seeks payback across the neon wastes of New Vegas, swaying the war between NCR, Legion, and Mr. House.",
      quote: "TRUTH IS... THE GAME WAS RIGGED FROM THE START.",
      rank: "Rank #1 Post-Apocalyptic RPG",
      membersCount: "1.9M Players",
      trailerUrl: "https://www.youtube.com/embed/v7xME0aG99w",
      tags: ["Courier", "Mojave", "Obsidian", "NCR", "New Vegas"],
      totalUnits: 80,
      unitType: "hours"
    },
    {
      id: "death-stranding-game",
      title: "Death Stranding Director's Cut",
      originalTitle: "Death Stranding",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1850570/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/gmECX1DvE9RiTeiKVPV7ndJTX8o.jpg",
      rating: 9.0,
      ratingCount: "1.2M",
      year: 2019,
      ongoing: false,
      runtimeOrChapters: "60 Hours",
      ageRating: "M - Mature 17+",
      genres: ["Sci-Fi", "Open World", "Cinematic", "Asynchronous Co-op"],
      platformOrStudio: "Kojima Productions / 505 Games",
      synopsis: "In a shattered future where an afterlife event called the Death Stranding severed civilization, Sam Porter Bridges treks across America to reconnect isolated cities with the Chiral Network.",
      quote: "TOMORROW IS IN YOUR HANDS.",
      rank: "Rank #1 Strand Game",
      membersCount: "1.2M Players",
      trailerUrl: "https://www.youtube.com/embed/tCI396HyHbQ",
      tags: ["Hideo Kojima", "Norman Reedus", "BB", "Timefall", "Porters"],
      totalUnits: 60,
      unitType: "hours"
    },
    {
      id: "doom-eternal",
      title: "DOOM Eternal",
      originalTitle: "DOOM Eternal",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/5n2P0F537K8Nl559Z9W3UvE3k2N.jpg",
      rating: 9.3,
      ratingCount: "1.6M",
      year: 2020,
      ongoing: false,
      runtimeOrChapters: "25 Hours",
      ageRating: "M - Mature 17+",
      genres: ["FPS", "Action", "Gore", "Metal Soundtrack"],
      platformOrStudio: "id Software / Bethesda",
      synopsis: "Hell's armies have invaded Earth. Become the Doom Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity.",
      quote: "RIP AND TEAR, UNTIL IT IS DONE.",
      rank: "Rank #1 Fast-Paced Arena Shooter",
      membersCount: "1.6M Players",
      trailerUrl: "https://www.youtube.com/embed/_k3z5eE0y9U",
      tags: ["Doom Slayer", "id Software", "Heavy Metal", "BFG", "Glory Kill"],
      totalUnits: 25,
      unitType: "hours"
    },
    {
      id: "portal-2",
      title: "Portal 2",
      originalTitle: "Portal 2",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/tC3P1K9n7q8E2m5N4X6p8V1x9yP.jpg",
      rating: 9.8,
      ratingCount: "2.8M",
      year: 2011,
      ongoing: false,
      runtimeOrChapters: "15 Hours",
      ageRating: "E10+",
      genres: ["Puzzle", "Sci-Fi", "Comedy", "First-Person"],
      platformOrStudio: "Valve",
      synopsis: "Chell awakens in the decaying Aperture Science Enrichment Center, teaming up with moronic AI Wheatley and encountering sadistic potato-battery GLaDOS in peerless portal puzzle design.",
      quote: "THE CAKE IS A LIE.",
      rank: "Rank #1 Highest Rated Steam Game of All Time",
      membersCount: "2.8M Players",
      trailerUrl: "https://www.youtube.com/embed/tax4gW7Mr40",
      tags: ["GLaDOS", "Portal Gun", "Valve", "Wheatley", "Aperture Science"],
      totalUnits: 15,
      unitType: "hours"
    },
    {
      id: "half-life-alyx",
      title: "Half-Life: Alyx",
      originalTitle: "Half-Life: Alyx",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/546560/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/r2Vq7M6Q9Y2K6N8V1X9Z3p4b8U5.jpg",
      rating: 9.7,
      ratingCount: "820K",
      year: 2020,
      ongoing: false,
      runtimeOrChapters: "18 Hours",
      ageRating: "M - Mature 17+",
      genres: ["VR", "FPS", "Sci-Fi", "Atmospheric"],
      platformOrStudio: "Valve",
      synopsis: "Valve's VR return to the Half-Life series set between Half-Life and Half-Life 2, following Alyx Vance as she mounts an impossible fight against the Combine occupation.",
      quote: "WELCOME BACK TO CITY 17.",
      rank: "Rank #1 Virtual Reality Masterpiece",
      membersCount: "820K Players",
      trailerUrl: "https://www.youtube.com/embed/O2W0N3uKXmo",
      tags: ["Alyx Vance", "City 17", "Combine", "Valve", "VR"],
      totalUnits: 18,
      unitType: "hours"
    },
    {
      id: "bioshock-infinite",
      title: "BioShock Infinite",
      originalTitle: "BioShock Infinite",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/8870/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/uCu4jN6r2F5pT5L7cQ7z0m0z0bE.jpg",
      rating: 9.2,
      ratingCount: "1.9M",
      year: 2013,
      ongoing: false,
      runtimeOrChapters: "20 Hours",
      ageRating: "M - Mature 17+",
      genres: ["FPS", "Story-Rich", "Sci-Fi", "Steampunk"],
      platformOrStudio: "Irrational Games / 2K",
      synopsis: "Former Pinkerton agent Booker DeWitt is sent to the floating sky-city of Columbia in 1912 to rescue Elizabeth, a mysterious woman with the power to tear holes in spacetime.",
      quote: "BRING US THE GIRL, AND WIPE AWAY THE DEBT.",
      rank: "Rank #1 Multiverse Sci-Fi Shooter",
      membersCount: "1.9M Players",
      trailerUrl: "https://www.youtube.com/embed/bLHW78X1XeE",
      tags: ["Columbia", "Booker DeWitt", "Elizabeth", "Lighthouses", "Ken Levine"],
      totalUnits: 20,
      unitType: "hours"
    },
    {
      id: "horizon-zero-dawn",
      title: "Horizon Zero Dawn",
      originalTitle: "Horizon Zero Dawn",
      category: "gaming",
      mediaType: "game",
      coverImage: "https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/header.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/vFlq03Xl3gJ5vB8k9M1P4E2m3X8.jpg",
      rating: 9.1,
      ratingCount: "1.8M",
      year: 2017,
      ongoing: false,
      runtimeOrChapters: "60 Hours",
      ageRating: "T - Teen",
      genres: ["Action RPG", "Open World", "Sci-Fi", "Post-Apocalyptic"],
      platformOrStudio: "Guerrilla Games / PlayStation",
      synopsis: "In a lush post-apocalyptic world ruled by colossal animalistic machines, tribal outcast Aloy embarks on a journey to uncover her origins and the catastrophe of the Old Ones.",
      quote: "I WAS NEVER AN OUTCAST FROM THE EARTH.",
      rank: "Rank #1 Post-Post-Apocalypse",
      membersCount: "1.8M Players",
      trailerUrl: "https://www.youtube.com/embed/u4-FCsiF5x4",
      tags: ["Aloy", "Thunderjaw", "Guerrilla", "Bow", "Machines"],
      totalUnits: 60,
      unitType: "hours"
    }
  ],
  moreManga: [
    {
      id: "dandadan-manga-extra",
      title: "Chainsaw Man: Buddy Stories",
      originalTitle: "チェンソーマン ぶでぃストーリーズ",
      category: "manga",
      mediaType: "manga",
      coverImage: "https://cdn.myanimelist.net/images/manga/3/258767.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/eU0Tg9n7pD3F5qFzZ3jU7a2V7uT.jpg",
      rating: 8.2,
      ratingCount: "80K",
      year: 2021,
      ongoing: false,
      runtimeOrChapters: "4 Chapters",
      ageRating: "Teen",
      genres: ["Action", "Comedy", "Shonen"],
      platformOrStudio: "Jump J-Books / Tatsuki Fujimoto",
      synopsis: "Spin-off collection detailing the detective adventures of Power and Denji, Kishibe and Quanxi's youth, and Aki and Himeno's first mission together.",
      quote: "NOBEL PRIZE WINNER POWER!",
      rank: "Top Spin-off Manga",
      membersCount: "80K Members",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Power", "Denji", "Kishibe", "Fujimoto", "Buddy Stories"],
      totalUnits: 4,
      unitType: "chapters"
    },
    {
      id: "look-back-manga",
      title: "Look Back",
      originalTitle: "ルックバック",
      category: "manga",
      mediaType: "manga",
      coverImage: "https://cdn.myanimelist.net/images/manga/1/249339.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/7eHn2P5Z0m2P1V6E4L2U9m8N7x1.jpg",
      rating: 8.8,
      ratingCount: "220K",
      year: 2021,
      ongoing: false,
      runtimeOrChapters: "140 Pages (One-Shot)",
      ageRating: "Teen",
      genres: ["Drama", "Slice of Life", "Award Winning"],
      platformOrStudio: "Shonen Jump+ / Tatsuki Fujimoto",
      synopsis: "Two young girls connected by their profound passion for drawing manga form an artistic partnership that spans seasons, facing unforeseen tragedy and the relentless desire to create.",
      quote: "DON'T LOOK BACK IN ANGER.",
      rank: "Rank #1 Critical One-Shot of the Decade",
      membersCount: "220K Members",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Fujimoto", "Art", "Friendship", "One-Shot", "Masterpiece"],
      totalUnits: 1,
      unitType: "chapters"
    },
    {
      id: "goodbye-eri",
      title: "Goodbye, Eri",
      originalTitle: "さよなら絵梨",
      category: "manga",
      mediaType: "manga",
      coverImage: "https://cdn.myanimelist.net/images/manga/2/261050.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/nQ4iV63Kq2GqZ3kM8p0V2uF6m1N.jpg",
      rating: 8.7,
      ratingCount: "210K",
      year: 2022,
      ongoing: false,
      runtimeOrChapters: "200 Pages (One-Shot)",
      ageRating: "Teen",
      genres: ["Drama", "Psychological", "Supernatural"],
      platformOrStudio: "Shonen Jump+ / Tatsuki Fujimoto",
      synopsis: "Yuta films his mother's final days, screening his movie at school to derision before meeting a mysterious girl named Eri who asks him to film her until she dies.",
      quote: "EVERY MOVIE NEEDS A PINCH OF FANTASY.",
      rank: "Rank #1 Cinematic Manga Framing",
      membersCount: "210K Members",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Cinema", "Fujimoto", "Explosion", "Vampire", "Smartphone"],
      totalUnits: 1,
      unitType: "chapters"
    },
    {
      id: "uzumaki-deluxe",
      title: "Tomie",
      originalTitle: "富江",
      category: "manga",
      mediaType: "manga",
      coverImage: "https://cdn.myanimelist.net/images/manga/3/258768.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/w2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
      rating: 8.0,
      ratingCount: "130K",
      year: 1987,
      ongoing: false,
      runtimeOrChapters: "20 Chapters (2 Vols)",
      ageRating: "Mature",
      genres: ["Horror", "Psychological", "Supernatural"],
      platformOrStudio: "Monthly Halloween / Junji Ito",
      synopsis: "An intoxicatingly beautiful high school girl drives men to homicidal madness, causing them to dismember her only for each severed piece to regenerate into another Tomie.",
      quote: "YOU CAN NEVER KILL TOMIE.",
      rank: "Rank #1 Femme Fatale Horror",
      membersCount: "130K Members",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Junji Ito", "Tomie", "Regeneration", "Gothic", "Cult Classic"],
      totalUnits: 20,
      unitType: "chapters"
    },
    {
      id: "dr-stone-manga",
      title: "Dr. STONE (Manga)",
      originalTitle: "Dr.STONE",
      category: "manga",
      mediaType: "manga",
      coverImage: "https://cdn.myanimelist.net/images/manga/3/193181.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/c4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
      rating: 8.4,
      ratingCount: "240K",
      year: 2017,
      ongoing: false,
      runtimeOrChapters: "232 Chapters (26 Vols)",
      ageRating: "Teen",
      genres: ["Adventure", "Sci-Fi", "Shonen"],
      platformOrStudio: "Weekly Shonen Jump / Riichiro Inagaki & Boichi",
      synopsis: "Boichi's dynamic hyper-detailed illustrations bring Riichiro Inagaki's science triumph to life, from inventing antibiotics to building a lunar rocket.",
      quote: "THIS IS THE POWER OF HUMAN CUMULATIVE SCIENCE.",
      rank: "Rank #1 Science Celebration",
      membersCount: "240K Members",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Boichi", "Senku", "Rocket", "Science", "Shonen Jump"],
      totalUnits: 232,
      unitType: "chapters"
    },
    {
      id: "tokyo-revengers-manga",
      title: "Tokyo Revengers",
      originalTitle: "東京卍リベンジャーズ",
      category: "manga",
      mediaType: "manga",
      coverImage: "https://cdn.myanimelist.net/images/manga/3/207033.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/yQxGv61nFqZ0nL0uF306b9qC0oT.jpg",
      rating: 8.0,
      ratingCount: "310K",
      year: 2017,
      ongoing: false,
      runtimeOrChapters: "278 Chapters (31 Vols)",
      ageRating: "Teen",
      genres: ["Action", "Drama", "Supernatural", "Shonen"],
      platformOrStudio: "Weekly Shonen Magazine / Ken Wakui",
      synopsis: "Takemichi Hanagaki time-leaps exactly 12 years into the past to save his middle school ex-girlfriend from being murdered by the Tokyo Manji Gang.",
      quote: "I WILL NEVER GIVE UP!",
      rank: "Rank #1 Delinquent Time Travel",
      membersCount: "310K Members",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Toman", "Mikey", "Draken", "Time Leap", "Wakui"],
      totalUnits: 278,
      unitType: "chapters"
    },
    {
      id: "gintama-manga",
      title: "Gintama",
      originalTitle: "銀魂",
      category: "manga",
      mediaType: "manga",
      coverImage: "https://cdn.myanimelist.net/images/manga/2/258769.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/p4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
      rating: 8.8,
      ratingCount: "190K",
      year: 2003,
      ongoing: false,
      runtimeOrChapters: "704 Chapters (77 Vols)",
      ageRating: "Teen",
      genres: ["Action", "Comedy", "Sci-Fi", "Shonen"],
      platformOrStudio: "Weekly Shonen Jump / Hideaki Sorachi",
      synopsis: "In an alternate Edo Japan conquered by extraterrestrial aliens called Amanto, silver-haired odd-jobs freelancer Gintoki Sakata does anything for rent with a wooden sword.",
      quote: "IF YOU HAVE TIME TO THINK OF A BEAUTIFUL END, LIVE BEAUTIFULLY UNTIL THE END.",
      rank: "Rank #1 Shonen Meta-Comedy",
      membersCount: "190K Members",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Gintoki", "Yorozuya", "Shinsengumi", "Sorachi", "Parody"],
      totalUnits: 704,
      unitType: "chapters"
    },
    {
      id: "jojos-part-5-golden-wind-manga",
      title: "JoJo's Bizarre Adventure: Golden Wind",
      originalTitle: "ジョジョの奇妙な冒険 Part5 黄金の風",
      category: "manga",
      mediaType: "manga",
      coverImage: "https://cdn.myanimelist.net/images/manga/2/258770.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/gmECX1DvE9RiTeiKVPV7ndJTX8o.jpg",
      rating: 8.6,
      ratingCount: "260K",
      year: 1995,
      ongoing: false,
      runtimeOrChapters: "155 Chapters (17 Vols)",
      ageRating: "Mature",
      genres: ["Action", "Supernatural", "Shonen"],
      platformOrStudio: "Weekly Shonen Jump / Hirohiko Araki",
      synopsis: "In 2001 Naples, Giorno Giovanna aims to reform Italian crime syndicate Passione from within as a 'Gang-Star' with his stand Golden Wind alongside Bruno Bucciarati.",
      quote: "I, GIORNO GIOVANNA, HAVE A DREAM.",
      rank: "Rank #1 Mafia Stand Battle",
      membersCount: "260K Members",
      trailerUrl: "https://www.youtube.com/embed/S8_YwFLCh4U",
      tags: ["Giorno", "Bucciarati", "Passione", "Stands", "Araki"],
      totalUnits: 155,
      unitType: "chapters"
    }
  ]
};
