module.exports = {
  movies: [
    {
      id: "oppenheimer",
      title: "Oppenheimer",
      originalTitle: "Oppenheimer",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      rating: 9.3,
      ratingCount: "2.4M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "180 Minutes",
      ageRating: "R",
      genres: ["Biography", "Drama", "History"],
      platformOrStudio: "Universal Pictures / Christopher Nolan",
      synopsis: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during the Manhattan Project.",
      quote: "NOW I AM BECOME DEATH, THE DESTROYER OF WORLDS.",
      rank: "Academy Award Winner - Best Picture",
      membersCount: "2.4M Members",
      trailerUrl: "https://www.youtube.com/embed/uYPbbksJxIg",
      featured: true,
      trending: true,
      tags: ["Christopher Nolan", "Cillian Murphy", "Manhattan Project", "IMAX", "Oscars"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "interstellar",
      title: "Interstellar",
      originalTitle: "Interstellar",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
      rating: 9.5,
      ratingCount: "3.2M",
      year: 2014,
      ongoing: false,
      runtimeOrChapters: "169 Minutes",
      ageRating: "PG-13",
      genres: ["Sci-Fi", "Adventure", "Drama"],
      platformOrStudio: "Paramount / Christopher Nolan",
      synopsis: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft through a wormhole in search of a new planet for humans.",
      quote: "DO NOT GO GENTLE INTO THAT GOOD NIGHT.",
      rank: "Rank #1 Modern Sci-Fi Masterpiece",
      membersCount: "3.2M Members",
      trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
      featured: true,
      tags: ["Nolan", "Hans Zimmer", "Black Hole", "Tesseract", "Gargantua"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "the-dark-knight",
      title: "The Dark Knight",
      originalTitle: "The Dark Knight",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1r5vsIRqqXqvm.jpg",
      rating: 9.8,
      ratingCount: "4.1M",
      year: 2008,
      ongoing: false,
      runtimeOrChapters: "152 Minutes",
      ageRating: "PG-13",
      genres: ["Action", "Crime", "Drama", "Thriller"],
      platformOrStudio: "Warner Bros. / Christopher Nolan",
      synopsis: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      quote: "WHY SO SERIOUS?",
      rank: "Rank #1 Comic Book Film in History",
      membersCount: "4.1M Members",
      trailerUrl: "https://www.youtube.com/embed/EXeTwQWrcwY",
      featured: true,
      trending: true,
      tags: ["Heath Ledger", "Joker", "Batman", "Nolan", "Gotham"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "inception",
      title: "Inception",
      originalTitle: "Inception",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
      rating: 9.4,
      ratingCount: "3.5M",
      year: 2010,
      ongoing: false,
      runtimeOrChapters: "148 Minutes",
      ageRating: "PG-13",
      genres: ["Action", "Sci-Fi", "Adventure"],
      platformOrStudio: "Warner Bros. / Christopher Nolan",
      synopsis: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      quote: "AN IDEA IS LIKE A VIRUS.",
      rank: "Rank #1 Mind-Heist Thriller",
      membersCount: "3.5M Members",
      trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
      tags: ["Dreams", "DiCaprio", "Totem", "Nolan", "Hans Zimmer"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "blade-runner-2049",
      title: "Blade Runner 2049",
      originalTitle: "Blade Runner 2049",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/sAtoMqDVhNDQBc3QJL3RF6hlxGq.jpg",
      rating: 9.3,
      ratingCount: "1.9M",
      year: 2017,
      ongoing: false,
      runtimeOrChapters: "164 Minutes",
      ageRating: "R",
      genres: ["Sci-Fi", "Mystery", "Cyberpunk", "Drama"],
      platformOrStudio: "Warner Bros. / Denis Villeneuve",
      synopsis: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
      quote: "ALL THE BEST MEMORIES ARE HERS.",
      rank: "Rank #1 Cyberpunk Cinema",
      membersCount: "1.9M Members",
      trailerUrl: "https://www.youtube.com/embed/gCcx85zbxz4",
      tags: ["Denis Villeneuve", "Cyberpunk", "Ryan Gosling", "Deakins", "Replicant"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "dune-part-one",
      title: "Dune: Part One",
      originalTitle: "Dune",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/eeijXm355vAUtq5lgwp2QIY9R62.jpg",
      rating: 9.1,
      ratingCount: "2.6M",
      year: 2021,
      ongoing: false,
      runtimeOrChapters: "155 Minutes",
      ageRating: "PG-13",
      genres: ["Sci-Fi", "Adventure", "Epic"],
      platformOrStudio: "Warner Bros. / Denis Villeneuve",
      synopsis: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
      quote: "FEAR IS THE MIND-KILLER.",
      rank: "Rank #1 Sci-Fi Adaptation",
      membersCount: "2.6M Members",
      trailerUrl: "https://www.youtube.com/embed/n9xhJrPXop4",
      tags: ["Arrakis", "Timothee Chalamet", "Villeneuve", "Sandworm", "Spice"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "spider-man-into-the-spider-verse",
      title: "Spider-Man: Into the Spider-Verse",
      originalTitle: "Spider-Man: Into the Spider-Verse",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/7d6woWBsig1VvMN9gyOkGTTLHf2.jpg",
      rating: 9.4,
      ratingCount: "2.8M",
      year: 2018,
      ongoing: false,
      runtimeOrChapters: "117 Minutes",
      ageRating: "PG",
      genres: ["Animation", "Action", "Adventure", "Sci-Fi"],
      platformOrStudio: "Sony Pictures Animation / Marvel",
      synopsis: "Teen Miles Morales becomes the new Spider-Man, joining five spider-powered individuals from alternate universes to stop a menace for all realities.",
      quote: "ANYONE CAN WEAR THE MASK. YOU COULD WEAR THE MASK.",
      rank: "Oscar Winner Best Animated Feature",
      membersCount: "2.8M Members",
      trailerUrl: "https://www.youtube.com/embed/tg52up16eq0",
      tags: ["Miles Morales", "Spider-Verse", "Multiverse", "Animation", "Sony"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "everything-everywhere-all-at-once",
      title: "Everything Everywhere All at Once",
      originalTitle: "Everything Everywhere All at Once",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/w3LxiVYPqrlxqP9Yue483o20BpB.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/70Aptmsy688gKjO5Pq91P7kS04A.jpg",
      rating: 9.2,
      ratingCount: "1.7M",
      year: 2022,
      ongoing: false,
      runtimeOrChapters: "139 Minutes",
      ageRating: "R",
      genres: ["Action", "Adventure", "Comedy", "Sci-Fi"],
      platformOrStudio: "A24 / Daniels",
      synopsis: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
      quote: "IN ANOTHER LIFE, I WOULD HAVE REALLY LIKED JUST DOING LAUNDRY AND TAXES WITH YOU.",
      rank: "Oscar Winner Best Picture",
      membersCount: "1.7M Members",
      trailerUrl: "https://www.youtube.com/embed/wxN1T1uxQ2g",
      tags: ["Multiverse", "A24", "Michelle Yeoh", "Ke Huy Quan", "Bagel"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "avengers-endgame",
      title: "Avengers: Endgame",
      originalTitle: "Avengers: Endgame",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
      rating: 9.1,
      ratingCount: "4.8M",
      year: 2019,
      ongoing: false,
      runtimeOrChapters: "181 Minutes",
      ageRating: "PG-13",
      genres: ["Action", "Sci-Fi", "Superhero"],
      platformOrStudio: "Marvel Studios / Disney",
      synopsis: "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions.",
      quote: "AVENGERS... ASSEMBLE.",
      rank: "Highest Grossing Comic Book Movie of All Time",
      membersCount: "4.8M Members",
      trailerUrl: "https://www.youtube.com/embed/TcMBFSGVi1c",
      tags: ["MCU", "Iron Man", "Captain America", "Thanos", "Infinity Stones"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "avengers-infinity-war",
      title: "Avengers: Infinity War",
      originalTitle: "Avengers: Infinity War",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/bOGkgRGdhrBYJSLv7KiTe9Bhbx0.jpg",
      rating: 9.2,
      ratingCount: "4.6M",
      year: 2018,
      ongoing: false,
      runtimeOrChapters: "149 Minutes",
      ageRating: "PG-13",
      genres: ["Action", "Sci-Fi", "Superhero"],
      platformOrStudio: "Marvel Studios / Disney",
      synopsis: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
      quote: "DREAD IT. RUN FROM IT. DESTINY ARRIVES ALL THE SAME.",
      rank: "Rank #1 Comic Crossover Event",
      membersCount: "4.6M Members",
      trailerUrl: "https://www.youtube.com/embed/6ZfuNTqbHE8",
      tags: ["Thanos", "The Snap", "Wakanda", "Thor", "Marvel"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "the-matrix",
      title: "The Matrix",
      originalTitle: "The Matrix",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
      rating: 9.4,
      ratingCount: "3.7M",
      year: 1999,
      ongoing: false,
      runtimeOrChapters: "136 Minutes",
      ageRating: "R",
      genres: ["Sci-Fi", "Action", "Cyberpunk"],
      platformOrStudio: "Warner Bros. / The Wachowskis",
      synopsis: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
      quote: "WELCOME TO THE DESERT OF THE REAL.",
      rank: "Rank #1 Cyberpunk Action Film",
      membersCount: "3.7M Members",
      trailerUrl: "https://www.youtube.com/embed/vKQi3bBA1y8",
      tags: ["Neo", "Morpheus", "Red Pill", "Bullet Time", "Cyberpunk"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "mad-max-fury-road",
      title: "Mad Max: Fury Road",
      originalTitle: "Mad Max: Fury Road",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/gL0bU9a0Z1N6X8k3P2q8V1x9yP.jpg",
      rating: 9.3,
      ratingCount: "2.3M",
      year: 2015,
      ongoing: false,
      runtimeOrChapters: "120 Minutes",
      ageRating: "R",
      genres: ["Action", "Adventure", "Post-Apocalyptic"],
      platformOrStudio: "Warner Bros. / George Miller",
      synopsis: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
      quote: "WHAT A LOVELY DAY!",
      rank: "Rank #1 Action Choreography Film",
      membersCount: "2.3M Members",
      trailerUrl: "https://www.youtube.com/embed/hEJnMQG99mM",
      tags: ["Furiosa", "Tom Hardy", "George Miller", "Wasteland", "V8"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "gladiator",
      title: "Gladiator",
      originalTitle: "Gladiator",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      rating: 9.2,
      ratingCount: "2.9M",
      year: 2000,
      ongoing: false,
      runtimeOrChapters: "155 Minutes",
      ageRating: "R",
      genres: ["Action", "Adventure", "Drama", "Historical"],
      platformOrStudio: "DreamWorks / Ridley Scott",
      synopsis: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
      quote: "ARE YOU NOT ENTERTAINED?",
      rank: "Oscar Winner Best Picture",
      membersCount: "2.9M Members",
      trailerUrl: "https://www.youtube.com/embed/owK1qxDselE",
      tags: ["Maximus", "Ridley Scott", "Colosseum", "Rome", "Russell Crowe"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "parasite-movie",
      title: "Parasite",
      originalTitle: "기생충 (Gisaengchung)",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
      rating: 9.3,
      ratingCount: "2.4M",
      year: 2019,
      ongoing: false,
      runtimeOrChapters: "132 Minutes",
      ageRating: "R",
      genres: ["Drama", "Thriller", "Dark Comedy"],
      platformOrStudio: "CJ Entertainment / Bong Joon-ho",
      synopsis: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
      quote: "YOU KNOW WHAT KIND OF PLAN NEVER FAILS? NO PLAN AT ALL.",
      rank: "First Foreign Film to Win Best Picture",
      membersCount: "2.4M Members",
      trailerUrl: "https://www.youtube.com/embed/5xH0hhMBwXg",
      tags: ["Bong Joon-ho", "Korea", "Thriller", "Class Struggle", "Oscars"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "pulp-fiction",
      title: "Pulp Fiction",
      originalTitle: "Pulp Fiction",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/suaEOtk1916guMe7qdZKi4LnIQf.jpg",
      rating: 9.3,
      ratingCount: "3.5M",
      year: 1994,
      ongoing: false,
      runtimeOrChapters: "154 Minutes",
      ageRating: "R",
      genres: ["Crime", "Drama"],
      platformOrStudio: "Miramax / Quentin Tarantino",
      synopsis: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      quote: "SAY 'WHAT' AGAIN, I DARE YOU!",
      rank: "Rank #1 Indie Cult Film",
      membersCount: "3.5M Members",
      trailerUrl: "https://www.youtube.com/embed/s7EdQ4FqbhY",
      tags: ["Tarantino", "Samuel L Jackson", "Travolta", "Nonlinear", "Dialogue"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "lotr-return-of-the-king",
      title: "The Lord of the Rings: The Return of the King",
      originalTitle: "The Lord of the Rings: The Return of the King",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
      rating: 9.7,
      ratingCount: "4.2M",
      year: 2003,
      ongoing: false,
      runtimeOrChapters: "201 Minutes",
      ageRating: "PG-13",
      genres: ["Action", "Adventure", "Drama", "Fantasy"],
      platformOrStudio: "New Line Cinema / Peter Jackson",
      synopsis: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      quote: "MY FRIENDS, YOU BOW TO NO ONE.",
      rank: "11 Academy Awards Sweep",
      membersCount: "4.2M Members",
      trailerUrl: "https://www.youtube.com/embed/r5X-hFf6Bwo",
      tags: ["Middle-earth", "Frodo", "Aragorn", "Tolkien", "Peter Jackson"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "fight-club",
      title: "Fight Club",
      originalTitle: "Fight Club",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
      rating: 9.2,
      ratingCount: "3.4M",
      year: 1999,
      ongoing: false,
      runtimeOrChapters: "139 Minutes",
      ageRating: "R",
      genres: ["Drama", "Thriller"],
      platformOrStudio: "20th Century Fox / David Fincher",
      synopsis: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
      quote: "FIRST RULE OF FIGHT CLUB: YOU DO NOT TALK ABOUT FIGHT CLUB.",
      rank: "Rank #1 Cult Thriller",
      membersCount: "3.4M Members",
      trailerUrl: "https://www.youtube.com/embed/qtRKdVHc-cE",
      tags: ["David Fincher", "Tyler Durden", "Brad Pitt", "Anti-Consumerism"],
      totalUnits: 1,
      unitType: "episodes"
    },
    {
      id: "godzilla-minus-one",
      title: "Godzilla Minus One",
      originalTitle: "ゴジラ-1.0",
      category: "movies",
      mediaType: "movie",
      coverImage: "https://image.tmdb.org/t/p/w780/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/bckxAAq9HPoEO7KLznP04pH38Q1.jpg",
      rating: 9.1,
      ratingCount: "1.2M",
      year: 2023,
      ongoing: false,
      runtimeOrChapters: "125 Minutes",
      ageRating: "PG-13",
      genres: ["Action", "Sci-Fi", "Drama", "Kaiju"],
      platformOrStudio: "Toho / Takashi Yamazaki",
      synopsis: "Post-war Japan is at its lowest point when a colossal atomic monstrosity emerges, devastating a broken populace struggling to survive.",
      quote: "CAN WE OVERCOME OUR DEVASTATION?",
      rank: "Oscar Winner Best Visual Effects",
      membersCount: "1.2M Members",
      trailerUrl: "https://www.youtube.com/embed/VvSrHIX5a-0",
      tags: ["Godzilla", "Toho", "Kaiju", "Japan", "Oscars"],
      totalUnits: 1,
      unitType: "episodes"
    }
  ],
  tvShows: [
    {
      id: "breaking-bad",
      title: "Breaking Bad",
      originalTitle: "Breaking Bad",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/9faGSFi5jam6pDWGNd0p8J25Aq5.jpg",
      rating: 9.8,
      ratingCount: "4.8M",
      year: 2008,
      ongoing: false,
      runtimeOrChapters: "62 Episodes (5 Seasons)",
      ageRating: "TV-MA",
      genres: ["Crime", "Drama", "Thriller"],
      platformOrStudio: "AMC / Sony Pictures Television",
      synopsis: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student to secure his family's future.",
      quote: "I AM THE ONE WHO KNOCKS.",
      rank: "Rank #1 Highest Rated TV Series of All Time",
      membersCount: "4.8M Members",
      trailerUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
      featured: true,
      trending: true,
      tags: ["Walter White", "Jesse Pinkman", "Heisenberg", "Vince Gilligan", "Masterpiece"],
      totalUnits: 62,
      unitType: "episodes"
    },
    {
      id: "better-call-saul",
      title: "Better Call Saul",
      originalTitle: "Better Call Saul",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
      rating: 9.5,
      ratingCount: "2.1M",
      year: 2015,
      ongoing: false,
      runtimeOrChapters: "63 Episodes (6 Seasons)",
      ageRating: "TV-MA",
      genres: ["Crime", "Drama", "Legal"],
      platformOrStudio: "AMC / Sony Pictures Television",
      synopsis: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.",
      quote: "IT'S ALL GOOD, MAN!",
      rank: "Rank #1 Character Pacing & Tragedy",
      membersCount: "2.1M Members",
      trailerUrl: "https://www.youtube.com/embed/HN4oydykJFc",
      tags: ["Jimmy McGill", "Saul Goodman", "Kim Wexler", "Vince Gilligan"],
      totalUnits: 63,
      unitType: "episodes"
    },
    {
      id: "game-of-thrones",
      title: "Game of Thrones",
      originalTitle: "Game of Thrones",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
      rating: 9.3,
      ratingCount: "5.2M",
      year: 2011,
      ongoing: false,
      runtimeOrChapters: "73 Episodes (8 Seasons)",
      ageRating: "TV-MA",
      genres: ["Action", "Adventure", "Drama", "Fantasy"],
      platformOrStudio: "HBO",
      synopsis: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
      quote: "WINTER IS COMING.",
      rank: "Most Awarded Drama Series in Emmy History",
      membersCount: "5.2M Members",
      trailerUrl: "https://www.youtube.com/embed/KPLWWIOCOOQ",
      featured: true,
      tags: ["Westeros", "Daenerys", "Jon Snow", "Iron Throne", "Dragons"],
      totalUnits: 73,
      unitType: "episodes"
    },
    {
      id: "house-of-the-dragon",
      title: "House of the Dragon",
      originalTitle: "House of the Dragon",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/etj8E2o0yt0iAOP9a1k05c11fQ.jpg",
      rating: 9.1,
      ratingCount: "2.6M",
      year: 2022,
      ongoing: true,
      runtimeOrChapters: "18 Episodes",
      ageRating: "TV-MA",
      genres: ["Action", "Adventure", "Drama", "Fantasy"],
      platformOrStudio: "HBO",
      synopsis: "The story of the Targaryen civil war that took place about 200 years before events depicted in Game of Thrones, tearing the realm apart with dragon fire.",
      quote: "DREAMS DIDN'T MAKE US KINGS. DRAGONS DID.",
      rank: "Rank #1 Fantasy Prequel",
      membersCount: "2.6M Members",
      trailerUrl: "https://www.youtube.com/embed/DotnJ7tTA34",
      tags: ["Targaryen", "Rhaenyra", "Daemon", "Dragons", "HBO"],
      totalUnits: 18,
      unitType: "episodes"
    },
    {
      id: "succession",
      title: "Succession",
      originalTitle: "Succession",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/7DTknnvdh89n05bHkP2q8V1x9yP.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/wPU78OPN4BYEgWYdXyg0phMee61.jpg",
      rating: 9.4,
      ratingCount: "1.8M",
      year: 2018,
      ongoing: false,
      runtimeOrChapters: "39 Episodes (4 Seasons)",
      ageRating: "TV-MA",
      genres: ["Drama"],
      platformOrStudio: "HBO",
      synopsis: "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their aging father steps down from the company.",
      quote: "YOU HAVE TO BE A KILLER.",
      rank: "Emmy Best Drama Winner",
      membersCount: "1.8M Members",
      trailerUrl: "https://www.youtube.com/embed/OzYxJV_rmE8",
      tags: ["Roy Family", "Kendall", "Logan Roy", "HBO", "Corporate"],
      totalUnits: 39,
      unitType: "episodes"
    },
    {
      id: "severance",
      title: "Severance",
      originalTitle: "Severance",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/p7mB6w1jXkZ6nN4X6p8V1x9yP.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/t2Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
      rating: 9.2,
      ratingCount: "1.4M",
      year: 2022,
      ongoing: true,
      runtimeOrChapters: "19 Episodes (2 Seasons)",
      ageRating: "TV-MA",
      genres: ["Sci-Fi", "Thriller", "Mystery"],
      platformOrStudio: "Apple TV+",
      synopsis: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives; when a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.",
      quote: "PLEASE ENJOY EACH FACT EQUALLY.",
      rank: "Rank #1 Modern Dystopian Mystery",
      membersCount: "1.4M Members",
      trailerUrl: "https://www.youtube.com/embed/xEQP4VVuyrY",
      tags: ["Lumon", "Mark Scout", "Severance", "Apple TV+", "Corporate Horror"],
      totalUnits: 19,
      unitType: "episodes"
    },
    {
      id: "stranger-things",
      title: "Stranger Things",
      originalTitle: "Stranger Things",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      rating: 9.1,
      ratingCount: "4.1M",
      year: 2016,
      ongoing: true,
      runtimeOrChapters: "34 Episodes (4 Seasons)",
      ageRating: "TV-14",
      genres: ["Sci-Fi", "Horror", "Drama"],
      platformOrStudio: "Netflix / Duffer Brothers",
      synopsis: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
      quote: "FRIENDS DON'T LIE.",
      rank: "Netflix Most Watched Sci-Fi",
      membersCount: "4.1M Members",
      trailerUrl: "https://www.youtube.com/embed/b9EkMc79ZSU",
      tags: ["Upside Down", "Eleven", "Hawkins", "Demogorgon", "80s"],
      totalUnits: 34,
      unitType: "episodes"
    },
    {
      id: "chernobyl",
      title: "Chernobyl",
      originalTitle: "Chernobyl",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/uCu4jN6r2F5pT5L7cQ7z0m0z0bE.jpg",
      rating: 9.6,
      ratingCount: "2.3M",
      year: 2019,
      ongoing: false,
      runtimeOrChapters: "5 Episodes (Miniseries)",
      ageRating: "TV-MA",
      genres: ["Drama", "History", "Thriller"],
      platformOrStudio: "HBO / Sky",
      synopsis: "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
      quote: "WHAT IS THE COST OF LIES?",
      rank: "Highest Rated Miniseries in History",
      membersCount: "2.3M Members",
      trailerUrl: "https://www.youtube.com/embed/s9APLXM9Ei8",
      tags: ["Nuclear", "Valery Legasov", "HBO", "History", "Disaster"],
      totalUnits: 5,
      unitType: "episodes"
    },
    {
      id: "peaky-blinders",
      title: "Peaky Blinders",
      originalTitle: "Peaky Blinders",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/p4Z1k4P9m7Q8M6N4X6p8V1x9yP.jpg",
      rating: 9.2,
      ratingCount: "2.7M",
      year: 2013,
      ongoing: false,
      runtimeOrChapters: "36 Episodes (6 Seasons)",
      ageRating: "TV-MA",
      genres: ["Crime", "Drama", "Historical"],
      platformOrStudio: "BBC / Netflix",
      synopsis: "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
      quote: "BY ORDER OF THE PEAKY BLINDERS!",
      rank: "Rank #1 British Crime Drama",
      membersCount: "2.7M Members",
      trailerUrl: "https://www.youtube.com/embed/oVzVdvGIC7U",
      tags: ["Tommy Shelby", "Cillian Murphy", "Birmingham", "Razor", "BBC"],
      totalUnits: 36,
      unitType: "episodes"
    },
    {
      id: "daredevil-tv",
      title: "Daredevil",
      originalTitle: "Marvel's Daredevil",
      category: "tv-shows",
      mediaType: "tv",
      coverImage: "https://image.tmdb.org/t/p/w780/QWbPaDxiB6LW2vdaDr7MBlR12W.jpg",
      bannerImage: "https://image.tmdb.org/t/p/w1280/7eHn2P5Z0m2P1V6E4L2U9m8N7x1.jpg",
      rating: 9.3,
      ratingCount: "2.2M",
      year: 2015,
      ongoing: false,
      runtimeOrChapters: "39 Episodes (3 Seasons)",
      ageRating: "TV-MA",
      genres: ["Action", "Crime", "Drama", "Superhero"],
      platformOrStudio: "Marvel / Netflix",
      synopsis: "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil, engaging in brutal hallway fights against Wilson Fisk.",
      quote: "I'M NOT SEEKING PENANCE FOR WHAT I'VE DONE. I'M ASKING FORGIVENESS FOR WHAT I'M ABOUT TO DO.",
      rank: "Rank #1 Gritty Superhero TV Series",
      membersCount: "2.2M Members",
      trailerUrl: "https://www.youtube.com/embed/n83s6NO1NE0",
      tags: ["Matt Murdock", "Kingpin", "Hallway Fight", "Hell's Kitchen", "Marvel"],
      totalUnits: 39,
      unitType: "episodes"
    }
  ]
};
